import type {
  StageDeliverable,
  Typology,
} from "@/lib/types";

const ALL: Typology[] = ["house", "townhouse", "apartment"];
const APT: Typology[] = ["apartment"];

export type DeliverableCheckSpec = {
  id: string;
  stageId: string;
  deliverableId: string;
  title: string;
  detail: string;
  appliesTo: Typology[];
  required: boolean;
  references: string[];
};

function drawing(
  id: string,
  stageId: string,
  title: string,
  summary: string,
): StageDeliverable {
  return { id, stageId, kind: "drawing", title, summary, appliesTo: ALL };
}

function document(
  id: string,
  stageId: string,
  title: string,
  summary: string,
): StageDeliverable {
  return { id, stageId, kind: "document", title, summary, appliesTo: ALL };
}

function check(
  id: string,
  stageId: string,
  deliverableId: string,
  title: string,
  detail: string,
  references: string[],
  appliesTo: Typology[] = ALL,
): DeliverableCheckSpec {
  return {
    id,
    stageId,
    deliverableId,
    title,
    detail,
    appliesTo,
    required: true,
    references,
  };
}

export const STAGE_DELIVERABLES: StageDeliverable[] = [
  drawing(
    "del-pd-site",
    "pre-design",
    "Site information drawing",
    "A site plan that carries title, survey, overlays and keyed photos before sketching starts.",
  ),
  drawing(
    "del-sk-concept",
    "concept",
    "Concept sketch set",
    "Plans and massing for the preferred option the client can sign.",
  ),
  drawing(
    "del-dd-set",
    "design-development",
    "Design development set",
    "Coordinated plans, elevations and sections ready to lodge or to freeze for documentation.",
  ),
  drawing(
    "del-tp-set",
    "town-planning",
    "Town planning drawing set",
    "The application drawings and assessment sheets. Mark N/A on the job if no planning permit is required.",
  ),
  drawing(
    "del-cd-working",
    "documentation",
    "Working drawings",
    "The building-permit working drawing set, coordinated with endorsed planning drawings.",
  ),
  drawing(
    "del-cd-demo",
    "documentation",
    "Demolition and existing conditions",
    "Demo and existing-conditions plans showing what is retained, removed and protected.",
  ),
  drawing(
    "del-cd-site",
    "documentation",
    "Site plan",
    "Set-out, levels, services, access and neighbouring interfaces on the working site plan.",
  ),
  drawing(
    "del-cd-ga",
    "documentation",
    "General arrangement plans",
    "Floor plans coordinated with structure, services, fire, wet areas and access.",
  ),
  drawing(
    "del-cd-rcp",
    "documentation",
    "Reflected ceiling plans",
    "Ceiling heights, finishes, lighting, mechanical and fire devices, checked against structure.",
  ),
  drawing(
    "del-cd-elev",
    "documentation",
    "Elevations, sections and details",
    "Heights, levels, material junctions and construction details that match the plans.",
  ),
  drawing(
    "del-cd-roof",
    "documentation",
    "Roof plan",
    "Falls, gutters, downpipes, plant, flashings and safe roof access.",
  ),
  document(
    "del-cd-schedules",
    "documentation",
    "Door, window and materials schedules",
    "Schedules that match the drawings and call up glass, hardware and products.",
  ),
  document(
    "del-cd-spec",
    "documentation",
    "Specification",
    "Written spec that matches the working drawing revision and cites NCC 2025.",
  ),
  document(
    "del-tn-set",
    "tender",
    "Tender set",
    "The issued drawings, spec, addenda and tender form sent to builders.",
  ),
  drawing(
    "del-ca-ifc",
    "contract-admin",
    "For-construction issue",
    "The stamped for-construction set issued to the builder and the relevant building surveyor.",
  ),
  document(
    "del-pc-record",
    "practical-completion",
    "Defects list and PC record",
    "Inspection notes, defects list, handover items and the practical completion certificate or letter.",
  ),
  document(
    "del-dlp-register",
    "defects-liability",
    "Defects close-out register",
    "Open and closed defects through the contractual defects liability period.",
  ),
  document(
    "del-fc-pack",
    "final-certificate",
    "Final certificate pack",
    "Final inspection, warranties, security release notes and the archive of this job.",
  ),
  document(
    "del-poe-record",
    "post-occupancy",
    "Post-occupancy evaluation record",
    "Seasonal comfort, energy and landscape notes after people have lived in the building.",
  ),
];

export const DELIVERABLE_CHECKS: DeliverableCheckSpec[] = [
  check(
    "dw-pd-titleblock",
    "pre-design",
    "del-pd-site",
    "Title block, north, scale and revision",
    "Project name, address, north point, scale (or NTS), date and revision are on the sheet.",
    ["ARBV Guideline — Client–architect agreements", "Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-pd-boundaries",
    "pre-design",
    "del-pd-site",
    "Title boundaries, easements and covenants plotted",
    "Current title, plan of subdivision, easements, covenants and S173 agreements are plotted or noted on the drawing.",
    ["Land Use Victoria title search"],
  ),
  check(
    "dw-pd-overlays",
    "pre-design",
    "del-pd-site",
    "Zone, overlays and hazard notes",
    "Zone, overlays, flood, bushfire and heritage notes that affect siting are on the drawing or a keyed schedule.",
    ["Victoria Planning Provisions", "Planning scheme maps"],
  ),
  check(
    "dw-pd-existing",
    "pre-design",
    "del-pd-site",
    "Existing buildings, trees, services and photos",
    "Existing buildings, significant trees, services and photo locations are keyed to the plan.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-sk-titleblock",
    "concept",
    "del-sk-concept",
    "Title block and option labels",
    "Each sketch sheet has a title block, option name and date so the preferred scheme can be identified later.",
    ["ARBV Guideline — Client–architect agreements"],
  ),
  check(
    "dw-sk-plans",
    "concept",
    "del-sk-concept",
    "Plans, massing and storeys",
    "Plans and massing show dwelling count, storeys and a readable scale or key dimensions.",
    ["VPP Clause 54", "VPP Clause 55", "VPP Clause 58"],
  ),
  check(
    "dw-sk-solar",
    "concept",
    "del-sk-concept",
    "Orientation and 7-star testing",
    "North, living-room orientation and a note on NatHERS / 7-star testing of the preferred option.",
    ["NatHERS", "NCC 2025 energy efficiency (H6)"],
  ),
  check(
    "dw-sk-option",
    "concept",
    "del-sk-concept",
    "Preferred option for client sign-off",
    "The preferred option is labelled and ready for the client to sign before design development.",
    ["ARBV Guideline — Client–architect agreements"],
  ),
  check(
    "dw-dd-index",
    "design-development",
    "del-dd-set",
    "Drawing index and revision",
    "A drawing index lists every DD sheet. Revision and date match across the set.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-dd-coord",
    "design-development",
    "del-dd-set",
    "Plans, elevations and sections coordinated",
    "Plans, elevations and sections agree on levels, setbacks, openings and roof form.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-dd-esd",
    "design-development",
    "del-dd-set",
    "Materials, ESD and amenity notes",
    "Materials, ESD and amenity notes needed for lodgement or documentation freeze are on the drawings.",
    ["NCC 2025 (ABCB)", "Better Apartments Design Standards"],
  ),
  check(
    "dw-dd-consult",
    "design-development",
    "del-dd-set",
    "Consultant inputs referenced",
    "Structural and services inputs are overlayed or listed so clashes are visible before documentation.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-tp-title",
    "town-planning",
    "del-tp-set",
    "Title block matches the application",
    "Project name, address, revision and drawing numbers match the planning application form.",
    ["Planning and Environment Act 1987 (Vic)"],
  ),
  check(
    "dw-tp-assessment",
    "town-planning",
    "del-tp-set",
    "Clause 54 / 55 / 58 assessment drawings",
    "Neighbourhood and site description, shadow, garden area and other assessment sheets required by the applicable clause are in the set — or the job is marked N/A if no permit is required.",
    ["VPP Clause 54", "VPP Clause 55", "VPP Clause 58"],
  ),
  check(
    "dw-tp-summary",
    "town-planning",
    "del-tp-set",
    "Development summary table",
    "Heights, setbacks, garden area, parking, site coverage and dwelling mix are tabulated on a drawing.",
    ["VPP Clause 54", "VPP Clause 55", "VPP Clause 58"],
  ),
  check(
    "dw-tp-neighbour",
    "town-planning",
    "del-tp-set",
    "Neighbourhood and site description",
    "Streetscape, adjoining secluded private open space and existing conditions are drawn, not only photographed.",
    ["VPP Clause 54", "VPP Clause 55"],
  ),
  check(
    "dw-cd-index",
    "documentation",
    "del-cd-working",
    "Working drawing index and revisions",
    "The drawing index, revisions and dates match the set issued for building permit.",
    ["Building Act 1993 (Vic)", "Building Regulations 2018 (Vic)"],
  ),
  check(
    "dw-cd-coord",
    "documentation",
    "del-cd-working",
    "Plans, elevations, sections and details coordinated",
    "Architectural sheets agree with each other before they go to the relevant building surveyor.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-ncc",
    "documentation",
    "del-cd-working",
    "NCC 2025 notes on the drawings",
    "Livable housing, energy, waterproofing and condensation notes required by NCC 2025 (Vic from 1 May 2026) are on the set or clearly referenced to the spec.",
    ["NCC 2025 (ABCB)", "NCC 2025 Victorian variations (BPC)"],
  ),
  check(
    "dw-cd-endorsed",
    "documentation",
    "del-cd-working",
    "Matches endorsed planning drawings",
    "Working drawings match endorsed planning drawings, or approved variations are clouded and noted.",
    ["Planning and Environment Act 1987 (Vic)"],
  ),
  check(
    "dw-cd-north",
    "documentation",
    "del-cd-working",
    "Solar north matches the survey",
    "North point is solar north from the survey, not title north. Recheck against the site survey before issue.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-scale",
    "documentation",
    "del-cd-working",
    "Bar scale and print check",
    "Every sheet has a bar scale or stated scale. Print a full-size sheet and check it with a scale rule before issuing paper or PDFs that a quantity surveyor may scale.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-stamp",
    "documentation",
    "del-cd-working",
    "Issue stamp and date",
    "Title block is complete. Stamp the issue (preliminary, planning, tender or contract) and date. Cover-sheet drawing list matches the set.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-legend",
    "documentation",
    "del-cd-working",
    "Legends, tags and cross-references",
    "Legends cover abbreviations, materials, wall types and finishes. Room names, door and window numbers, wall tags, grids, section and elevation markers, and detail references agree across the set.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-demo-retain",
    "documentation",
    "del-cd-demo",
    "Retain versus demolish noted",
    "Every existing feature to stay or go is noted across the site — buildings, fences, gates, vegetation and paving. Retained walls are solid; demolished walls are dashed.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-demo-trees",
    "documentation",
    "del-cd-demo",
    "Trees to retain and tree protection zones",
    "Trees to be retained are shown with tree protection zones. Coordinate with any planning permit landscape or tree conditions.",
    ["Planning and Environment Act 1987 (Vic)", "VPP Clause 54 / 55 / 58 landscaping"],
  ),
  check(
    "dw-cd-demo-survey",
    "documentation",
    "del-cd-demo",
    "Existing levels and structure from survey",
    "Existing ground levels, pits, slabs, parapets, roofs, services, footings and columns match the survey. Check walls and columns back to the survey.",
    ["Land Use Victoria title search", "Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-demo-protect",
    "documentation",
    "del-cd-demo",
    "Protection works, compound and crossings",
    "Protection of adjoining property and crossings is noted. Show the skip, site shed and any hoarding. Coordinate with structural and civil for underpinning or propping on the boundary.",
    ["Building Act 1993 (Vic)", "Building Regulations 2018 (Vic)"],
  ),
  check(
    "dw-cd-site-title",
    "documentation",
    "del-cd-site",
    "Boundaries, easements and setbacks",
    "Boundary and easement dimensions and bearings match the title. Setbacks from all boundaries are dimensioned. Set-out is from a known grid or survey point.",
    ["Land Use Victoria title search", "Building Regulations 2018 Part 5"],
  ),
  check(
    "dw-cd-site-civil",
    "documentation",
    "del-cd-site",
    "Levels, crossovers and stormwater discharge",
    "Spot levels or contours, kerbs, channels, crossovers, pits and the stormwater point of discharge are shown. Confirm grades at every building entry with civil drawings and livable-housing / access requirements.",
    ["NCC 2025 Livable Housing Design", "NCC 2025 (ABCB)"],
  ),
  check(
    "dw-cd-site-services",
    "documentation",
    "del-cd-site",
    "Meters, fire and electrical plant on site",
    "Authority meters, hydrants, boosters, substations or main switchboards, and external lighting are located with height where it matters. Coordinate with electrical, hydraulic and the fire engineer.",
    ["NCC 2025 (ABCB)", "Building Act 1993 (Vic)"],
  ),
  check(
    "dw-cd-site-context",
    "documentation",
    "del-cd-site",
    "Adjoining dwellings, landscape and waste",
    "Adjoining dwellings, landscape (garden, grass, paving), bin storage and collection, site access, and parking bays with dimensions are on the plan. Coordinate paving and retaining with civil and landscape.",
    ["VPP Clause 52.06", "VPP Clause 54 / 55 / 58"],
  ),
  check(
    "dw-cd-ga-coord",
    "documentation",
    "del-cd-ga",
    "Plans match elevations; name the responsible party",
    "Wall thicknesses, windows and materials match elevations. Remove “by others”; name the consultant or trade. Beams, voids, eaves, canopies and bulkheads over are dashed.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-ga-fire",
    "documentation",
    "del-cd-ga",
    "Fire and acoustic walls, hydrants and egress",
    "Fire-rated and acoustic walls are tagged and not broken for plumbing. Show hydrants, hose cabinets, extinguishers and the fire indicator panel. Confirm travel distances and emergency-door size with the building surveyor and fire engineer.",
    ["NCC 2025 (ABCB)", "Building Act 1993 (Vic)"],
  ),
  check(
    "dw-cd-ga-wet",
    "documentation",
    "del-cd-ga",
    "Wet areas, wastes, falls and membranes",
    "Plumbing fixtures sit on suitable walls. Show floor wastes or trench grates with falls, wet-area membranes, hose cocks, downpipes and any water tank (size, location, purpose). Finished floor levels stay flush at finish changes.",
    ["AS 3740", "NCC 2025 Part H2"],
  ),
  check(
    "dw-cd-ga-access",
    "documentation",
    "del-cd-ga",
    "Doors, stairs and circulation",
    "Every door is numbered, including glazed doors; check swing and size. Stairs show direction, riser count, finishes and a cut-stringer note where needed. Confirm stairs and wheelchair turning / latch-side clearances with NCC 2025 and AS 1428.1.",
    ["NCC 2025 (ABCB)", "NCC 2025 Livable Housing Design", "AS 1428.1"],
  ),
  check(
    "dw-cd-ga-types",
    "documentation",
    "del-cd-ga",
    "Apartment, kitchen and bathroom type tags",
    "Apartment or room-type, kitchen and bathroom type tags are on the plans and match the schedules.",
    ["Better Apartments Design Standards", "Clause 58"],
    APT,
  ),
  check(
    "dw-cd-rcp-heights",
    "documentation",
    "del-cd-rcp",
    "Ceiling heights, finishes and access panels",
    "Ceiling finishes, heights or springing heights, bulkheads, pelmets and access hatches are shown. Note fire-rated and acoustic ceilings.",
    ["NCC 2025 (ABCB)", "Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-rcp-services",
    "documentation",
    "del-cd-rcp",
    "Lighting, grilles and indoor units",
    "Lighting layout, supply and return grilles, and indoor air-conditioning units are shown and coordinated with electrical and mechanical. Outdoor condensers are located. No clash with door swings.",
    ["NCC 2025 (ABCB)", "Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-rcp-detection",
    "documentation",
    "del-cd-rcp",
    "Smoke, thermal and security devices",
    "Smoke alarms, thermal detectors, speakers and security sensors are shown to the NCC and the brief. Coordinate with the electrical set and the building surveyor.",
    ["NCC 2025 (ABCB)", "Building Regulations 2018 (Vic)"],
  ),
  check(
    "dw-cd-rcp-structure",
    "documentation",
    "del-cd-rcp",
    "Skylights, voids and services vs structure",
    "Skylights, voids and service shafts are shown. Confirm they do not clash with roof structure, trusses, beams or slab thickness. Allow 250 mm for heating ducts and 350 mm for cooling where those services run in the ceiling.",
    ["NCC 2025 (ABCB)", "Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-elev-heights",
    "documentation",
    "del-cd-elev",
    "Heights match endorsed planning drawings",
    "Building heights match endorsed town-planning drawings. Show natural ground, cut ground, fall of ground, FFL, FCL, SSL, eaves and parapet RLs. Existing buildings to remain have survey heights.",
    ["Planning and Environment Act 1987 (Vic)", "Building Act 1993 (Vic) s 24"],
  ),
  check(
    "dw-cd-elev-junctions",
    "documentation",
    "del-cd-elev",
    "Material junctions, DPC and movement joints",
    "Every material junction is resolved. Show damp-proof course, weep holes, tanking, slab-edge finish, expansion joints and hatch patterns that match the schedule. Walls run to the underside of slab or beam unless noted, with deflection heads where needed.",
    ["NCC 2025 Part H2", "NCC 2025 (ABCB)"],
  ),
  check(
    "dw-cd-elev-openings",
    "documentation",
    "del-cd-elev",
    "Window operation, sills and tags",
    "Window tags, opening type and sill material/location are on the elevations and match the schedule. Note voids. Show the boundary line dashed.",
    ["AS 1288", "Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-elev-stairs",
    "documentation",
    "del-cd-elev",
    "Stairs, balustrades and ground clearance",
    "Stair goings and risers work with the levels (nominally 250 mm going, 190 mm riser unless the NCC solution differs). Balustrade extent, fixing and material are noted or referred to a detail. Check falls from steps and paving (max 900 mm to natural ground unless a barrier is required). Allow 250 mm clearance under a suspended floor where used.",
    ["NCC 2025 (ABCB)", "AS 1428.1"],
  ),
  check(
    "dw-cd-roof-drain",
    "documentation",
    "del-cd-roof",
    "Gutters, downpipes and overflows",
    "Gutter size is calculated. Show 1:100 fall direction, rainwater heads, sumps and overflow outlets. Downpipes do not clash with walls, footings or work below.",
    ["NCC 2025 (ABCB)", "NCC 2025 Part H2"],
  ),
  check(
    "dw-cd-roof-plant",
    "documentation",
    "del-cd-roof",
    "Plant, structure and flashings",
    "Roof-top plant has a location agreed with consultants. Structure can take the load. Show barge, parapet, apron, ridge and penetration flashings, roof finish tags and base metal thickness.",
    ["NCC 2025 (ABCB)", "Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-roof-penet",
    "documentation",
    "del-cd-roof",
    "Penetrations, flues and skylights",
    "Vents, flues, skylights and other penetrations are located and flashed. Confirm they miss structure and the ceiling layout.",
    ["NCC 2025 (ABCB)", "NCC 2025 condensation"],
  ),
  check(
    "dw-cd-roof-access",
    "documentation",
    "del-cd-roof",
    "Safe roof access",
    "Catwalks, anchor points, platforms and ladders needed to maintain plant and gutters are shown.",
    ["Occupational Health and Safety Act 2004 (Vic)", "NCC 2025 (ABCB)"],
  ),
  check(
    "doc-cd-doors",
    "documentation",
    "del-cd-schedules",
    "Door and window schedule vs drawings",
    "Indicative sizes, opening type and direction, and fire doors/seals/closers match plans, elevations, RCPs and joinery. Note AS 1288 glazing. Fire doors coordinated with the building surveyor.",
    ["AS 1288", "NCC 2025 (ABCB)"],
  ),
  check(
    "doc-cd-hardware",
    "documentation",
    "del-cd-schedules",
    "Hardware, restrictors and ventilation",
    "Hardware is noted or directed to a hardware schedule, dimensioned from finished floor and a known edge. Include flywire, blinds, opening restrictors, friction stays on awnings/casements, and trickle vents to habitable rooms where used. Full-height glass is laminated or toughened as required.",
    ["AS 1288", "NCC 2025 (ABCB)"],
  ),
  check(
    "doc-cd-sills",
    "documentation",
    "del-cd-schedules",
    "Sill heights and lintels",
    "Sill levels are dimensioned above finished floor. Lintels match the structural set. Sliding-door and operable-wall weights and tracks are coordinated with the structural engineer.",
    ["NCC 2025 (ABCB)", "Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "doc-cd-materials",
    "documentation",
    "del-cd-schedules",
    "Materials, FFE and finishes schedules",
    "Each scheduled item names manufacturer, product, code, colour/finish and overall size. Cover internal and external materials, fixtures, fittings, equipment, door hardware, insulation, paint, signage and joinery.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "doc-spec-rev",
    "documentation",
    "del-cd-spec",
    "Specification revision matches the drawings",
    "The spec revision and date match the working drawing issue.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "doc-spec-ncc",
    "documentation",
    "del-cd-spec",
    "NCC 2025 and standards cited",
    "The spec cites NCC 2025 Volume Two / Housing Provisions and the Australian Standards actually used.",
    ["NCC 2025 (ABCB)", "Standards Australia"],
  ),
  check(
    "doc-spec-finishes",
    "documentation",
    "del-cd-spec",
    "Finishes, waterproofing and bushfire (if any)",
    "Finishes, wet-area waterproofing and, if the lot is BAL-rated, bushfire-construction requirements are called up.",
    ["NCC 2025 damp and weatherproofing (H2)", "Building Regulations 2018 (Vic)"],
  ),
  check(
    "doc-spec-prelim",
    "documentation",
    "del-cd-spec",
    "Preliminaries match the building contract",
    "Preliminaries, PC sums and provisional sums match what will be tendered or contracted.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-tn-list",
    "tender",
    "del-tn-set",
    "Issued drawings and spec listed",
    "A transmittal or issue sheet lists every drawing and spec section sent to tenderers.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "doc-tn-addenda",
    "tender",
    "del-tn-set",
    "Addenda recorded",
    "Each addendum is numbered, dated and issued to every tenderer.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "doc-tn-form",
    "tender",
    "del-tn-set",
    "Tender form and selection criteria",
    "The tender form, closing time and selection criteria are in the set.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-tn-sums",
    "tender",
    "del-tn-set",
    "PC and provisional sums listed",
    "Known prime-cost and provisional sums are listed so tenders can be compared.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "dw-ca-ifc",
    "contract-admin",
    "del-ca-ifc",
    "Issued-for-construction stamp and revision",
    "The set is stamped or titled for construction and carries a unique revision.",
    ["Building Act 1993 (Vic)"],
  ),
  check(
    "dw-ca-permit",
    "contract-admin",
    "del-ca-ifc",
    "Building-permit drawings distinguished",
    "Building-permit drawings are distinct from tender sketches so the builder is not building an old issue.",
    ["Building Act 1993 (Vic)", "Building Regulations 2018 (Vic)"],
  ),
  check(
    "dw-ca-rfi",
    "contract-admin",
    "del-ca-ifc",
    "RFIs and site instructions that change drawings",
    "RFIs and site instructions that change the set are clouded or listed against the current revision.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-ca-issue",
    "contract-admin",
    "del-ca-ifc",
    "Latest set issued to builder and RBS",
    "The current issue has been sent to the builder and the relevant building surveyor.",
    ["Building Act 1993 (Vic)"],
  ),
  check(
    "doc-pc-inspect",
    "practical-completion",
    "del-pc-record",
    "Inspection date, attendees and weather",
    "The PC inspection record names who attended, the date and weather.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-pc-defects",
    "practical-completion",
    "del-pc-record",
    "Defects listed by location",
    "Defects are listed by room or location, with photos where they help.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-pc-handover",
    "practical-completion",
    "del-pc-record",
    "Keys, manuals and certificates listed",
    "Keys, operation manuals, occupancy permit and certificates are listed as handed over.",
    ["Building Act 1993 (Vic)", "Building Regulations 2018 (Vic)"],
  ),
  check(
    "doc-pc-cert",
    "practical-completion",
    "del-pc-record",
    "Practical completion certificate or letter",
    "The PC certificate or letter is on the project record with this list attached.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-dlp-dates",
    "defects-liability",
    "del-dlp-register",
    "DLP start and end dates",
    "The register records contractual DLP start and end dates.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-dlp-open",
    "defects-liability",
    "del-dlp-register",
    "Open and closed defects with dates",
    "Each defect has raised and closed dates, or is still open.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "doc-dlp-bond",
    "defects-liability",
    "del-dlp-register",
    "Apartment bond windows (if captured)",
    "If the building is a captured apartment building, the 15–18 and 21–24 month bond inspection windows are noted. Otherwise mark N/A.",
    ["Apartment developer bond"],
  ),
  check(
    "doc-dlp-notices",
    "defects-liability",
    "del-dlp-register",
    "Builder notifications on file",
    "Written notices to the builder about remaining defects are stored with this register.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-fc-inspect",
    "final-certificate",
    "del-fc-pack",
    "Final inspection notes",
    "A final inspection after DLP is recorded, or the reason it was not required.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-fc-warr",
    "final-certificate",
    "del-fc-pack",
    "Warranties and certificates listed",
    "Domestic building insurance, occupancy permit and product warranties are listed in the pack.",
    ["Domestic Building Contracts Act 1995 (Vic)", "Building Act 1993 (Vic)"],
  ),
  check(
    "doc-fc-security",
    "final-certificate",
    "del-fc-pack",
    "Security and retention release notes",
    "Retention or security release is noted against the contract.",
    ["Domestic Building Contracts Act 1995 (Vic)", "Security of Payment Act 2002 (Vic)"],
  ),
  check(
    "doc-fc-archive",
    "final-certificate",
    "del-fc-pack",
    "Archive of permits, drawings and this ZIP",
    "The pack lists where permits, the drawing record and this project ZIP are stored.",
    ["Victorian Architects Code of Professional Conduct", "Architects Act 1991 (Vic)"],
  ),
  check(
    "doc-poe-dates",
    "post-occupancy",
    "del-poe-record",
    "Interview or visit dates",
    "Seasonal visit or interview dates are recorded (winter and summer where possible).",
    ["ARBV"],
  ),
  check(
    "doc-poe-comfort",
    "post-occupancy",
    "del-poe-record",
    "Comfort, energy and condensation notes",
    "Occupant notes on winter/summer comfort, bills or NatHERS vs actual, and condensation are written down.",
    ["NCC 2025 energy efficiency (H6)", "NatHERS"],
  ),
  check(
    "doc-poe-landscape",
    "post-occupancy",
    "del-poe-record",
    "Landscape establishment",
    "Deep soil, planting and irrigation notes after the first seasons.",
    ["VPP Clause 55", "VPP Clause 58"],
  ),
  check(
    "doc-poe-lessons",
    "post-occupancy",
    "del-poe-record",
    "Lessons for the next Victorian residential job",
    "A short list of what to change on the next house, townhouse or apartment.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
];
