import type {
  StageDeliverable,
  Typology,
} from "@/lib/types";

const ALL: Typology[] = ["house", "townhouse", "apartment"];

export type DeliverableCheckSpec = {
  id: string;
  stageId: string;
  deliverableId: string;
  title: string;
  detail: string;
  appliesTo: Typology[];
  required: boolean;
  references: string[];
};

function drawing(
  id: string,
  stageId: string,
  title: string,
  summary: string,
): StageDeliverable {
  return { id, stageId, kind: "drawing", title, summary, appliesTo: ALL };
}

function document(
  id: string,
  stageId: string,
  title: string,
  summary: string,
): StageDeliverable {
  return { id, stageId, kind: "document", title, summary, appliesTo: ALL };
}

function check(
  id: string,
  stageId: string,
  deliverableId: string,
  title: string,
  detail: string,
  references: string[],
): DeliverableCheckSpec {
  return {
    id,
    stageId,
    deliverableId,
    title,
    detail,
    appliesTo: ALL,
    required: true,
    references,
  };
}

export const STAGE_DELIVERABLES: StageDeliverable[] = [
  drawing(
    "del-pd-site",
    "pre-design",
    "Site information drawing",
    "A site plan that carries title, survey, overlays and keyed photos before sketching starts.",
  ),
  drawing(
    "del-sk-concept",
    "concept",
    "Concept sketch set",
    "Plans and massing for the preferred option the client can sign.",
  ),
  drawing(
    "del-dd-set",
    "design-development",
    "Design development set",
    "Coordinated plans, elevations and sections ready to lodge or to freeze for documentation.",
  ),
  drawing(
    "del-tp-set",
    "town-planning",
    "Town planning drawing set",
    "The application drawings and assessment sheets. Mark N/A on the job if no planning permit is required.",
  ),
  drawing(
    "del-cd-working",
    "documentation",
    "Working drawings",
    "The building-permit working drawing set, coordinated with endorsed planning drawings.",
  ),
  document(
    "del-cd-spec",
    "documentation",
    "Specification",
    "Written spec that matches the working drawing revision and cites NCC 2025.",
  ),
  document(
    "del-tn-set",
    "tender",
    "Tender set",
    "The issued drawings, spec, addenda and tender form sent to builders.",
  ),
  drawing(
    "del-ca-ifc",
    "contract-admin",
    "For-construction issue",
    "The stamped for-construction set issued to the builder and the relevant building surveyor.",
  ),
  document(
    "del-pc-record",
    "practical-completion",
    "Defects list and PC record",
    "Inspection notes, defects list, handover items and the practical completion certificate or letter.",
  ),
  document(
    "del-dlp-register",
    "defects-liability",
    "Defects close-out register",
    "Open and closed defects through the contractual defects liability period.",
  ),
  document(
    "del-fc-pack",
    "final-certificate",
    "Final certificate pack",
    "Final inspection, warranties, security release notes and the archive of this job.",
  ),
  document(
    "del-poe-record",
    "post-occupancy",
    "Post-occupancy evaluation record",
    "Seasonal comfort, energy and landscape notes after people have lived in the building.",
  ),
];

export const DELIVERABLE_CHECKS: DeliverableCheckSpec[] = [
  check(
    "dw-pd-titleblock",
    "pre-design",
    "del-pd-site",
    "Title block, north, scale and revision",
    "Project name, address, north point, scale (or NTS), date and revision are on the sheet.",
    ["ARBV Guideline — Client–architect agreements", "Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-pd-boundaries",
    "pre-design",
    "del-pd-site",
    "Title boundaries, easements and covenants plotted",
    "Current title, plan of subdivision, easements, covenants and S173 agreements are plotted or noted on the drawing.",
    ["Land Use Victoria title search"],
  ),
  check(
    "dw-pd-overlays",
    "pre-design",
    "del-pd-site",
    "Zone, overlays and hazard notes",
    "Zone, overlays, flood, bushfire and heritage notes that affect siting are on the drawing or a keyed schedule.",
    ["Victoria Planning Provisions", "Planning scheme maps"],
  ),
  check(
    "dw-pd-existing",
    "pre-design",
    "del-pd-site",
    "Existing buildings, trees, services and photos",
    "Existing buildings, significant trees, services and photo locations are keyed to the plan.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-sk-titleblock",
    "concept",
    "del-sk-concept",
    "Title block and option labels",
    "Each sketch sheet has a title block, option name and date so the preferred scheme can be identified later.",
    ["ARBV Guideline — Client–architect agreements"],
  ),
  check(
    "dw-sk-plans",
    "concept",
    "del-sk-concept",
    "Plans, massing and storeys",
    "Plans and massing show dwelling count, storeys and a readable scale or key dimensions.",
    ["VPP Clause 54", "VPP Clause 55", "VPP Clause 58"],
  ),
  check(
    "dw-sk-solar",
    "concept",
    "del-sk-concept",
    "Orientation and 7-star testing",
    "North, living-room orientation and a note on NatHERS / 7-star testing of the preferred option.",
    ["NatHERS", "NCC 2025 energy efficiency (H6)"],
  ),
  check(
    "dw-sk-option",
    "concept",
    "del-sk-concept",
    "Preferred option for client sign-off",
    "The preferred option is labelled and ready for the client to sign before design development.",
    ["ARBV Guideline — Client–architect agreements"],
  ),
  check(
    "dw-dd-index",
    "design-development",
    "del-dd-set",
    "Drawing index and revision",
    "A drawing index lists every DD sheet. Revision and date match across the set.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-dd-coord",
    "design-development",
    "del-dd-set",
    "Plans, elevations and sections coordinated",
    "Plans, elevations and sections agree on levels, setbacks, openings and roof form.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-dd-esd",
    "design-development",
    "del-dd-set",
    "Materials, ESD and amenity notes",
    "Materials, ESD and amenity notes needed for lodgement or documentation freeze are on the drawings.",
    ["NCC 2025 (ABCB)", "Better Apartments Design Standards"],
  ),
  check(
    "dw-dd-consult",
    "design-development",
    "del-dd-set",
    "Consultant inputs referenced",
    "Structural and services inputs are overlayed or listed so clashes are visible before documentation.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-tp-title",
    "town-planning",
    "del-tp-set",
    "Title block matches the application",
    "Project name, address, revision and drawing numbers match the planning application form.",
    ["Planning and Environment Act 1987 (Vic)"],
  ),
  check(
    "dw-tp-assessment",
    "town-planning",
    "del-tp-set",
    "Clause 54 / 55 / 58 assessment drawings",
    "Neighbourhood and site description, shadow, garden area and other assessment sheets required by the applicable clause are in the set — or the job is marked N/A if no permit is required.",
    ["VPP Clause 54", "VPP Clause 55", "VPP Clause 58"],
  ),
  check(
    "dw-tp-summary",
    "town-planning",
    "del-tp-set",
    "Development summary table",
    "Heights, setbacks, garden area, parking, site coverage and dwelling mix are tabulated on a drawing.",
    ["VPP Clause 54", "VPP Clause 55", "VPP Clause 58"],
  ),
  check(
    "dw-tp-neighbour",
    "town-planning",
    "del-tp-set",
    "Neighbourhood and site description",
    "Streetscape, adjoining secluded private open space and existing conditions are drawn, not only photographed.",
    ["VPP Clause 54", "VPP Clause 55"],
  ),
  check(
    "dw-cd-index",
    "documentation",
    "del-cd-working",
    "Working drawing index and revisions",
    "The drawing index, revisions and dates match the set issued for building permit.",
    ["Building Act 1993 (Vic)", "Building Regulations 2018 (Vic)"],
  ),
  check(
    "dw-cd-coord",
    "documentation",
    "del-cd-working",
    "Plans, elevations, sections and details coordinated",
    "Architectural sheets agree with each other before they go to the relevant building surveyor.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-cd-ncc",
    "documentation",
    "del-cd-working",
    "NCC 2025 notes on the drawings",
    "Livable housing, energy, waterproofing and condensation notes required by NCC 2025 (Vic from 1 May 2026) are on the set or clearly referenced to the spec.",
    ["NCC 2025 (ABCB)", "NCC 2025 Victorian variations (BPC)"],
  ),
  check(
    "dw-cd-endorsed",
    "documentation",
    "del-cd-working",
    "Matches endorsed planning drawings",
    "Working drawings match endorsed planning drawings, or approved variations are clouded and noted.",
    ["Planning and Environment Act 1987 (Vic)"],
  ),
  check(
    "doc-spec-rev",
    "documentation",
    "del-cd-spec",
    "Specification revision matches the drawings",
    "The spec revision and date match the working drawing issue.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "doc-spec-ncc",
    "documentation",
    "del-cd-spec",
    "NCC 2025 and standards cited",
    "The spec cites NCC 2025 Volume Two / Housing Provisions and the Australian Standards actually used.",
    ["NCC 2025 (ABCB)", "Standards Australia"],
  ),
  check(
    "doc-spec-finishes",
    "documentation",
    "del-cd-spec",
    "Finishes, waterproofing and bushfire (if any)",
    "Finishes, wet-area waterproofing and, if the lot is BAL-rated, bushfire-construction requirements are called up.",
    ["NCC 2025 damp and weatherproofing (H2)", "Building Regulations 2018 (Vic)"],
  ),
  check(
    "doc-spec-prelim",
    "documentation",
    "del-cd-spec",
    "Preliminaries match the building contract",
    "Preliminaries, PC sums and provisional sums match what will be tendered or contracted.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-tn-list",
    "tender",
    "del-tn-set",
    "Issued drawings and spec listed",
    "A transmittal or issue sheet lists every drawing and spec section sent to tenderers.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "doc-tn-addenda",
    "tender",
    "del-tn-set",
    "Addenda recorded",
    "Each addendum is numbered, dated and issued to every tenderer.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "doc-tn-form",
    "tender",
    "del-tn-set",
    "Tender form and selection criteria",
    "The tender form, closing time and selection criteria are in the set.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-tn-sums",
    "tender",
    "del-tn-set",
    "PC and provisional sums listed",
    "Known prime-cost and provisional sums are listed so tenders can be compared.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "dw-ca-ifc",
    "contract-admin",
    "del-ca-ifc",
    "Issued-for-construction stamp and revision",
    "The set is stamped or titled for construction and carries a unique revision.",
    ["Building Act 1993 (Vic)"],
  ),
  check(
    "dw-ca-permit",
    "contract-admin",
    "del-ca-ifc",
    "Building-permit drawings distinguished",
    "Building-permit drawings are distinct from tender sketches so the builder is not building an old issue.",
    ["Building Act 1993 (Vic)", "Building Regulations 2018 (Vic)"],
  ),
  check(
    "dw-ca-rfi",
    "contract-admin",
    "del-ca-ifc",
    "RFIs and site instructions that change drawings",
    "RFIs and site instructions that change the set are clouded or listed against the current revision.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "dw-ca-issue",
    "contract-admin",
    "del-ca-ifc",
    "Latest set issued to builder and RBS",
    "The current issue has been sent to the builder and the relevant building surveyor.",
    ["Building Act 1993 (Vic)"],
  ),
  check(
    "doc-pc-inspect",
    "practical-completion",
    "del-pc-record",
    "Inspection date, attendees and weather",
    "The PC inspection record names who attended, the date and weather.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-pc-defects",
    "practical-completion",
    "del-pc-record",
    "Defects listed by location",
    "Defects are listed by room or location, with photos where they help.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-pc-handover",
    "practical-completion",
    "del-pc-record",
    "Keys, manuals and certificates listed",
    "Keys, operation manuals, occupancy permit and certificates are listed as handed over.",
    ["Building Act 1993 (Vic)", "Building Regulations 2018 (Vic)"],
  ),
  check(
    "doc-pc-cert",
    "practical-completion",
    "del-pc-record",
    "Practical completion certificate or letter",
    "The PC certificate or letter is on the project record with this list attached.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-dlp-dates",
    "defects-liability",
    "del-dlp-register",
    "DLP start and end dates",
    "The register records contractual DLP start and end dates.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-dlp-open",
    "defects-liability",
    "del-dlp-register",
    "Open and closed defects with dates",
    "Each defect has raised and closed dates, or is still open.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
  check(
    "doc-dlp-bond",
    "defects-liability",
    "del-dlp-register",
    "Apartment bond windows (if captured)",
    "If the building is a captured apartment building, the 15–18 and 21–24 month bond inspection windows are noted. Otherwise mark N/A.",
    ["Apartment developer bond"],
  ),
  check(
    "doc-dlp-notices",
    "defects-liability",
    "del-dlp-register",
    "Builder notifications on file",
    "Written notices to the builder about remaining defects are stored with this register.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-fc-inspect",
    "final-certificate",
    "del-fc-pack",
    "Final inspection notes",
    "A final inspection after DLP is recorded, or the reason it was not required.",
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  check(
    "doc-fc-warr",
    "final-certificate",
    "del-fc-pack",
    "Warranties and certificates listed",
    "Domestic building insurance, occupancy permit and product warranties are listed in the pack.",
    ["Domestic Building Contracts Act 1995 (Vic)", "Building Act 1993 (Vic)"],
  ),
  check(
    "doc-fc-security",
    "final-certificate",
    "del-fc-pack",
    "Security and retention release notes",
    "Retention or security release is noted against the contract.",
    ["Domestic Building Contracts Act 1995 (Vic)", "Security of Payment Act 2002 (Vic)"],
  ),
  check(
    "doc-fc-archive",
    "final-certificate",
    "del-fc-pack",
    "Archive of permits, drawings and this ZIP",
    "The pack lists where permits, the drawing record and this project ZIP are stored.",
    ["Victorian Architects Code of Professional Conduct", "Architects Act 1991 (Vic)"],
  ),
  check(
    "doc-poe-dates",
    "post-occupancy",
    "del-poe-record",
    "Interview or visit dates",
    "Seasonal visit or interview dates are recorded (winter and summer where possible).",
    ["ARBV"],
  ),
  check(
    "doc-poe-comfort",
    "post-occupancy",
    "del-poe-record",
    "Comfort, energy and condensation notes",
    "Occupant notes on winter/summer comfort, bills or NatHERS vs actual, and condensation are written down.",
    ["NCC 2025 energy efficiency (H6)", "NatHERS"],
  ),
  check(
    "doc-poe-landscape",
    "post-occupancy",
    "del-poe-record",
    "Landscape establishment",
    "Deep soil, planting and irrigation notes after the first seasons.",
    ["VPP Clause 55", "VPP Clause 58"],
  ),
  check(
    "doc-poe-lessons",
    "post-occupancy",
    "del-poe-record",
    "Lessons for the next Victorian residential job",
    "A short list of what to change on the next house, townhouse or apartment.",
    ["Victorian Architects Code of Professional Conduct"],
  ),
];
