import { sha256Json, templateChecksumPayload } from "@/lib/hash";
import type {
  ChecklistItem,
  GrokBotBrief,
  Stage,
  TemplateDocument,
  Typology,
} from "@/lib/types";
import { TEMPLATE_FORMAT, FORMAT_VERSION } from "@/lib/types";

const ALL: Typology[] = ["house", "townhouse", "apartment"];
const HOUSE: Typology[] = ["house"];
const TH: Typology[] = ["townhouse"];
const APT: Typology[] = ["apartment"];
const MULTI: Typology[] = ["townhouse", "apartment"];

const STAGES: Stage[] = [
  {
    id: "pre-design",
    number: 1,
    title: "Pre-design",
    summary:
      "Brief, title, planning context, budget and what is possible on the site before sketching.",
  },
  {
    id: "concept",
    number: 2,
    title: "Concept / sketch design",
    summary:
      "Options, massing and a preferred concept the client can sign, tested against Vic planning and 7-star orientation.",
  },
  {
    id: "design-development",
    number: 3,
    title: "Design development",
    summary:
      "Resolve the preferred scheme with consultants, materials, ESD and amenity so it is ready to lodge.",
  },
  {
    id: "town-planning",
    number: 4,
    title: "Town planning",
    summary:
      "Confirm whether a planning permit is required and run Clause 54, 55 or 58 through to endorsed plans.",
  },
  {
    id: "documentation",
    number: 5,
    title: "Construction documentation",
    summary:
      "Working drawings and specifications that match endorsed planning drawings and NCC 2022 for a building permit.",
  },
  {
    id: "tender",
    number: 6,
    title: "Tender and contractor selection",
    summary:
      "Issue the tender set, compare builders, and appoint under a written building contract.",
  },
  {
    id: "contract-admin",
    number: 7,
    title: "Building contract administration",
    summary:
      "Building permit, inspections, variations, progress certificates, and occupancy.",
  },
  {
    id: "practical-completion",
    number: 8,
    title: "Practical completion",
    summary:
      "Inspect, list defects, collect keys and manuals, and certify practical completion.",
  },
  {
    id: "defects-liability",
    number: 9,
    title: "Defects liability (post-occupancy)",
    summary:
      "Track and close defects during the contractual DLP and any apartment bond inspections.",
  },
  {
    id: "final-certificate",
    number: 10,
    title: "Final certificate",
    summary:
      "Issue the final certificate after DLP, start domestic building warranties, and archive the record.",
  },
  {
    id: "post-occupancy",
    number: 11,
    title: "Post-occupancy evaluation",
    summary:
      "Seasonal comfort, energy, landscape and lessons learned after people have lived in the building.",
  },
];

function item(
  id: string,
  stageId: string,
  title: string,
  detail: string,
  appliesTo: Typology[] = ALL,
  required = true,
  references: string[] = [],
): ChecklistItem {
  return {
    id,
    stageId,
    title,
    detail,
    appliesTo,
    required,
    references,
    grokbotId: `bot-${stageId}`,
  };
}

const ITEMS: ChecklistItem[] = [
  item(
    "pd-arbv",
    "pre-design",
    "Confirm architect registration",
    "Check the architect (and any company) is registered with the Architects Registration Board of Victoria before engagement.",
    ALL,
    true,
    ["ARBV — Find an architect", "Victorian Architects Code of Professional Conduct"],
  ),
  item(
    "pd-agreement",
    "pre-design",
    "Written client–architect agreement",
    "Do not start work until a written agreement is signed. Record stages, fees, consultants, and whether planning and contract administration are included.",
    ALL,
    true,
    ["ARBV Guideline — Client-architect agreements"],
  ),
  item(
    "pd-brief",
    "pre-design",
    "Project brief",
    "Record household or dwelling mix, accessibility, working from home, storage, parking, landscape, budget range, and must-not-change constraints.",
  ),
  item(
    "pd-title",
    "pre-design",
    "Title, easements, covenants and restrictions",
    "Obtain a current title, plan of subdivision, easements, covenants, S173 agreements, and any owners corporation rules that constrain siting or materials.",
    ALL,
    true,
    ["Land Use Victoria title search"],
  ),
  item(
    "pd-oc",
    "pre-design",
    "Owners corporation and common property",
    "Identify OC plan, common property, exclusive-use areas, and whether a special resolution is needed for works.",
    MULTI,
    true,
    ["Subdivision Act 1988", "Owners Corporations Act 2006"],
  ),
  item(
    "pd-planning-context",
    "pre-design",
    "Zone, overlays and planning scheme",
    "Record municipality, planning scheme, zone, overlays (heritage, flood, bushfire, special building, DDO, SLO, HO, BMO, LSIO, SBO) and whether a planning permit is likely.",
    ALL,
    true,
    ["Victoria Planning Provisions", "Planning scheme maps"],
  ),
  item(
    "pd-clauses",
    "pre-design",
    "Applicable residential clause",
    "House or small second dwelling: Clause 54 if a planning permit is required. Two or more dwellings / townhouses / low-rise apartments to three storeys: Clause 55 (Townhouse and Low-Rise Code). Apartments of five storeys or more: Clause 58. Confirm storeys and dwelling count.",
    ALL,
    true,
    ["VPP Clause 54", "VPP Clause 55", "VPP Clause 58"],
  ),
  item(
    "pd-survey",
    "pre-design",
    "Feature and level survey",
    "Commission a site survey with levels, trees, crossovers, services, adjoining windows and secluded private open space relevant to ResCode.",
  ),
  item(
    "pd-services",
    "pre-design",
    "Services and authority constraints",
    "Locate sewer, stormwater, water, power, gas, NBN, and any build-over or asset-protection requirements. Flag septic or unsewered lots.",
  ),
  item(
    "pd-hazards",
    "pre-design",
    "Bushfire, flood, contamination and heritage",
    "Record BAL if BMO or BAL construction may apply, flood levels, heritage citation, and potential contamination on infill lots.",
    ALL,
    true,
    ["AS 3959", "Building Regulations 2018", "Heritage Overlay"],
  ),
  item(
    "pd-budget",
    "pre-design",
    "Budget, program and GST",
    "Set a working construction budget, consultant budget, authority fees, and a program that includes planning time. Note GST treatment.",
  ),
  item(
    "pd-neighbours",
    "pre-design",
    "Neighbourhood context photos",
    "Photograph streetscape, adjoining dwellings, existing trees, and likely overlooking/overshadowing interfaces.",
    ALL,
    false,
  ),

  item(
    "cd-site-analysis",
    "concept",
    "Site analysis",
    "Sun path, prevailing wind, views, privacy, significant trees, slope, and street character. This feeds the design response.",
    ALL,
    true,
    ["Clause 54.01 / 55.01 neighbourhood and site description"],
  ),
  item(
    "cd-options",
    "concept",
    "Concept options",
    "Issue at least one preferred sketch scheme (and alternatives if the agreement requires). Record client comments against each.",
  ),
  item(
    "cd-massing",
    "concept",
    "Height, setbacks and garden area",
    "Test building height, street setback, site coverage, permeability and garden-area requirements of the zone before locking a plan.",
    HOUSE,
    true,
    ["GRZ/NRZ garden area", "Clause 54 neighbourhood character standards"],
  ),
  item(
    "cd-cl55",
    "concept",
    "Clause 55 deemed-to-comply check",
    "Run an early check against street setback, height, side/rear setbacks, walls on boundaries, site coverage, access, tree canopy and front fence. Flag where the Townhouse and Low-Rise Code deemed-to-comply path is intended.",
    TH,
    true,
    ["Clause 55 Townhouse and Low-Rise Code (from 31 March 2025)"],
  ),
  item(
    "cd-canopy",
    "concept",
    "Tree canopy target",
    "Design for 10% canopy cover on sites up to 1,000 m² and 20% above 1,000 m², counting existing trees where they will be retained.",
    TH,
    true,
    ["Clause 55 tree canopy"],
  ),
  item(
    "cd-apartments",
    "concept",
    "Apartment mix, communal space and BADS",
    "Set dwelling mix, apartment depths, communal open space, outlook and building separation against Better Apartments / Clause 55.07 or 58.",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 55.07", "Clause 58"],
  ),
  item(
    "cd-energy",
    "concept",
    "Orientation for 7-star NatHERS",
    "Lock living-room solar access, glazing areas, shading and thermal mass so a 7-star NatHERS outcome is plausible. Victoria requires NCC 2022 energy provisions from 1 May 2024.",
    ALL,
    true,
    ["NCC 2022", "NatHERS 7-star (Vic from 1 May 2024)"],
  ),
  item(
    "cd-livable",
    "concept",
    "Livable housing path of travel",
    "Plan a step-free path, entrance width, and adaptable bathroom location. For Class 2, at least 50% of dwellings must meet the NCC livable housing provisions (or the higher VPP standard where it applies).",
    ALL,
    true,
    ["NCC 2022 Livable Housing Design", "VBA accessibility and energy fact sheet"],
  ),
  item(
    "cd-parking",
    "concept",
    "Parking, crossovers and waste",
    "Check Clause 52.06 parking, crossover locations, visitor parking, and whether waste collection is kerbside or on-site.",
    ALL,
    true,
    ["Clause 52.06"],
  ),
  item(
    "cd-signoff",
    "concept",
    "Client sign-off of preferred concept",
    "Written approval of the preferred concept, with a cost check against the brief, before design development.",
  ),

  item(
    "dd-gas",
    "design-development",
    "Coordinated GA drawings",
    "Plans, sections and elevations at a scale suitable for planning, with levels, materials, and adjoining interfaces.",
  ),
  item(
    "dd-consultants",
    "design-development",
    "Consultant team engaged",
    "Appoint as needed: land surveyor, structural, civil/hydraulic, energy assessor, landscape, ESD, fire, acoustic, traffic, waste, geotech, quantity surveyor.",
  ),
  item(
    "dd-nathers",
    "design-development",
    "Preliminary NatHERS and whole-of-home",
    "Run a preliminary 7-star rating and whole-of-home assessment. Adjust fabric before planning freeze.",
    ALL,
    true,
    ["NatHERS", "NCC 2022 energy"],
  ),
  item(
    "dd-storm",
    "design-development",
    "Stormwater and permeability",
    "STORM or MUSIC assessment, on-site detention if required, and permeability consistent with the planning standard.",
    ALL,
    true,
    ["Clause 53.18 / stormwater", "Melbourne Water", "local WSUD policy"],
  ),
  item(
    "dd-amenity",
    "design-development",
    "Overlooking, overshadowing and daylight",
    "Prepare diagrams for overlooking, overshadowing of secluded private open space, daylight to existing windows, and protection of existing rooftop solar.",
    ALL,
    true,
    ["Clause 54/55 amenity standards"],
  ),
  item(
    "dd-landscape",
    "design-development",
    "Landscape and deep soil",
    "Landscape concept with canopy trees, deep-soil volumes, and front-garden character. Apartments: deep-soil / canopy tables in 55.07 or 58.03.",
    ALL,
    true,
    ["Clause 55.07 / 58.03 landscaping"],
  ),
  item(
    "dd-bess",
    "design-development",
    "ESD / BESS (apartments and larger townhouse sites)",
    "Where council policy requires it, prepare a BESS or equivalent ESD report covering energy, water, IEQ, stormwater and waste.",
    MULTI,
    false,
    ["local ESD policy", "BESS"],
  ),
  item(
    "dd-wind",
    "design-development",
    "Wind assessment",
    "Commission a wind assessment for apartment buildings of five storeys or more, and earlier if the site is exposed.",
    APT,
    false,
    ["Clause 58 wind impacts"],
  ),
  item(
    "dd-acoustic",
    "design-development",
    "Acoustic strategy",
    "Address road/rail noise, apartment-to-apartment acoustic separation, and plant noise. Required on busy transport corridors.",
    APT,
    false,
    ["Clause 58.04 / Better Apartments noise"],
  ),
  item(
    "dd-waste",
    "design-development",
    "Waste management plan",
    "Apartment (and larger townhouse) waste rooms, collection vehicle path, and council waste policy.",
    MULTI,
    false,
  ),
  item(
    "dd-client-lodge",
    "design-development",
    "Client approval to lodge planning",
    "Confirm the scheme, cost update, and authority to lodge with council (or to proceed to building permit if no planning permit is required).",
  ),

  item(
    "tp-need",
    "town-planning",
    "Confirm whether a planning permit is required",
    "Single dwellings on lots without overlays often proceed on a building permit only. Dual occupancy, townhouses, apartments, overlays and demolition commonly need a planning permit.",
    ALL,
    true,
    ["Planning and Environment Act 1987"],
  ),
  item(
    "tp-cl54",
    "town-planning",
    "Clause 54 assessment (house)",
    "If a permit is required for one dwelling or a small second dwelling, assess against Clause 54 including neighbourhood character, tree canopy and amenity (VC282 from 8 September 2025).",
    HOUSE,
    true,
    ["Clause 54", "Amendment VC282"],
  ),
  item(
    "tp-cl55",
    "town-planning",
    "Clause 55 assessment (townhouse / low-rise)",
    "Meet Clause 55 objectives. Where using deemed-to-comply standards, document each standard met. Otherwise provide an alternative design response against neighbourhood character policy.",
    TH,
    true,
    ["Clause 55", "Designing Better Medium Density Housing"],
  ),
  item(
    "tp-cl58",
    "town-planning",
    "Clause 58 assessment (apartments 5+ storeys)",
    "Lodge a Clause 58 assessment with urban context, building layout, amenity, internal space, and landscaping standards.",
    APT,
    true,
    ["Clause 58", "Better Apartments Design Standards"],
  ),
  item(
    "tp-nsd",
    "town-planning",
    "Neighbourhood and site description + design response",
    "Prepare the Clause 54.01 / 55.01 package: existing conditions, neighbourhood character and a design response that explains the scheme.",
  ),
  item(
    "tp-set",
    "town-planning",
    "Planning drawing set",
    "Site plan, floor plans, elevations, sections, shadow diagrams, materials, landscape, and development summary (site coverage, permeability, garden area, canopy, parking).",
  ),
  item(
    "tp-reports",
    "town-planning",
    "Supporting reports",
    "As required: traffic, waste, ESD/BESS, arborist, heritage, flood, bushfire, urban context, acoustic, wind, affordable housing.",
    ALL,
    false,
  ),
  item(
    "tp-lodge",
    "town-planning",
    "Lodge application and pay fees",
    "Lodge with the responsible authority, keep the application number, and diary statutory clocks.",
  ),
  item(
    "tp-rfi",
    "town-planning",
    "Further information and advertising",
    "Respond to s54 further information. Track notice/advertising, objectors, and any consultation.",
    ALL,
    false,
    ["Planning and Environment Act ss 52, 54"],
  ),
  item(
    "tp-permit",
    "town-planning",
    "Planning permit and endorsed plans",
    "Receive the permit, read every condition, and obtain endorsed plans. Diary secondary consents, expiry, and plans-to-be-endorsed conditions.",
  ),
  item(
    "tp-subdivision",
    "town-planning",
    "Subdivision and statement of compliance",
    "For townhouses (and apartment lots), run the plan of subdivision, OC schedule, and statement of compliance in parallel with construction as required.",
    MULTI,
    false,
    ["Subdivision Act 1988"],
  ),

  item(
    "doc-tp-match",
    "documentation",
    "Match endorsed town planning drawings",
    "Check every planning condition and endorsed dimension before issuing a building-permit set. Record any secondary consent needed.",
  ),
  item(
    "doc-working",
    "documentation",
    "Working drawings and specification",
    "Issue a coordinated architectural set and specification suitable for tender and for the building surveyor.",
  ),
  item(
    "doc-ncc",
    "documentation",
    "NCC 2022 compliance notes",
    "Classify the building (Class 1a / 1b / 2 / 7a carpark etc.), document performance solutions, fire, moisture, energy and accessibility.",
    ALL,
    true,
    ["NCC 2022", "Building Act 1993"],
  ),
  item(
    "doc-energy",
    "documentation",
    "Final NatHERS 7-star and whole-of-home",
    "Final energy report for the building permit application lodged after 1 May 2024.",
    ALL,
    true,
    ["NCC 2022", "NatHERS"],
  ),
  item(
    "doc-livable",
    "documentation",
    "Livable housing details",
    "Dimension step-free paths, 850 mm clear entries, sanitary facilities and adaptable bathrooms. Apartments: identify the 50% of dwellings that meet Design A or B.",
    ALL,
    true,
    ["NCC 2022 Livable Housing Design"],
  ),
  item(
    "doc-condensation",
    "documentation",
    "Condensation management",
    "Detail vapour control, roof and wall ventilation, and wet-area ventilation per NCC 2022 condensation provisions.",
    ALL,
    true,
    ["NCC 2022 condensation"],
  ),
  item(
    "doc-structure",
    "documentation",
    "Structural, civil and services drawings",
    "Coordinated structure, stormwater, sewer, electrical, mechanical and fire drawings issued as part of the permit set.",
  ),
  item(
    "doc-waterproofing",
    "documentation",
    "Waterproofing and wet areas",
    "Specify AS 3740 wet-area systems, balcony membranes, and inspection hold points.",
    ALL,
    true,
    ["AS 3740"],
  ),
  item(
    "doc-part5",
    "documentation",
    "Part 5 siting vs planning permit",
    "Where no planning permit exists, check Part 5 of the Building Regulations (siting). Where a planning permit exists, apply regulation 68 so the building permit is not inconsistent with the planning permit.",
    HOUSE,
    true,
    ["Building Regulations 2018 Part 5", "reg 68"],
  ),
  item(
    "doc-manual",
    "documentation",
    "Building manual inputs",
    "Collect information needed for the building manual / operations information that the 2025 inspection and manual reforms expect at occupancy.",
    ALL,
    false,
    ["Building Amendment (Building Manuals and Mandatory Inspections) Regulations 2025"],
  ),

  item(
    "tn-set",
    "tender",
    "Tender set issued",
    "Issue drawings, specification, planning permit, and known site constraints. Record tender closing date.",
  ),
  item(
    "tn-rfi",
    "tender",
    "Tender RFIs",
    "Answer builder queries in writing and issue addenda to all tenderers.",
  ),
  item(
    "tn-compare",
    "tender",
    "Tender comparison",
    "Compare price, program, qualifications, PC sums, and exclusions on the same basis.",
  ),
  item(
    "tn-builder",
    "tender",
    "Builder registration and insurance",
    "Confirm VBA/BPC registration, domestic building insurance where required, and public liability.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995", "Building and Plumbing Commission"],
  ),
  item(
    "tn-contract",
    "tender",
    "Building contract executed",
    "Execute a written contract (ABIC, HIA or other) with the drawings and spec listed. Architect as contract administrator if engaged for that stage.",
  ),
  item(
    "tn-rbs",
    "tender",
    "Appoint relevant building surveyor",
    "Client appoints a registered building surveyor. Do not let the builder appoint the RBS for the client.",
    ALL,
    true,
    ["Building Act 1993"],
  ),

  item(
    "ca-permit",
    "contract-admin",
    "Building permit issued",
    "Building permit received before work starts. Check it lists the correct drawings, stages, and mandatory notification stages.",
    ALL,
    true,
    ["Building Act 1993"],
  ),
  item(
    "ca-inspections",
    "contract-admin",
    "Mandatory inspections program",
    "Diary foundation, framing, waterproofing, occupancy and any additional 2025 notification stages. Builders must notify the RBS before covering work.",
    ALL,
    true,
    ["Building Regulations 2018 mandatory notifications"],
  ),
  item(
    "ca-meetings",
    "contract-admin",
    "Site meetings and minutes",
    "Minute directions, RFIs, and quality issues. Architect remains impartial if administering the contract.",
    ALL,
    true,
    ["ARBV Code — administer building contracts impartially"],
  ),
  item(
    "ca-variations",
    "contract-admin",
    "Variations",
    "Price and approve variations in writing before the work proceeds. Keep a running cost report.",
  ),
  item(
    "ca-claims",
    "contract-admin",
    "Progress claims and certificates",
    "Assess claims, issue certificates, and track retention or security under the contract.",
  ),
  item(
    "ca-oc",
    "contract-admin",
    "Occupancy permit or final inspection",
    "RBS issues an occupancy permit (or certificate of final inspection). Apartments: occupancy before residents move in, typically for the building / each part as applicable.",
    ALL,
    true,
    ["Building Act 1993 occupancy permit"],
  ),
  item(
    "ca-bond",
    "contract-admin",
    "Apartment developer bond (if captured)",
    "For residential apartment buildings over three storeys with a building permit issued from 1 July 2027, lodge a 2% bond with the BPC before applying for occupancy. Notice to BPC as required. Transitional: regulations from 1 July 2026.",
    APT,
    false,
    ["Building Legislation Amendment (Buyer Protections) Act 2025"],
  ),
  item(
    "ca-oc-setup",
    "contract-admin",
    "Owners corporation set-up",
    "OC registered, insurance, first meeting, common property schedule, and building manual handed over.",
    MULTI,
    false,
  ),

  item(
    "pc-inspect",
    "practical-completion",
    "Practical completion inspection",
    "Architect inspects against the contract documents. Major defects delay PC; minor defects go on the list.",
  ),
  item(
    "pc-list",
    "practical-completion",
    "Defects and incomplete works list",
    "Issue a dated list. Builder must close items. Occupancy permit does not waive contractual defects.",
  ),
  item(
    "pc-handover",
    "practical-completion",
    "Keys, warranties, as-builts and manuals",
    "Collect keys, appliance warranties, cleaning, as-built services drawings, operation manuals, and the building manual.",
  ),
  item(
    "pc-certificate",
    "practical-completion",
    "Certificate of practical completion",
    "Issue PC. This starts the defects liability period. Record the date in the project JSON.",
  ),

  item(
    "dlp-period",
    "defects-liability",
    "Defects liability period diary",
    "Record DLP start (PC date) and end. Typical residential contracts use 12 months; check the executed contract.",
  ),
  item(
    "dlp-track",
    "defects-liability",
    "Defects register",
    "Log each defect with date, location, photo, item id, and close-out date. Empty notes are allowed; do not delete closed items.",
  ),
  item(
    "dlp-bond-prelim",
    "defects-liability",
    "Apartment bond preliminary inspection (15–18 months)",
    "If the developer bond scheme applies, arrange the qualified building assessor inspection 15–18 months after occupancy and give the developer an opportunity to rectify.",
    APT,
    false,
    ["Developer bond scheme — BPC"],
  ),
  item(
    "dlp-bond-final",
    "defects-liability",
    "Apartment bond final inspection (21–24 months)",
    "If the preliminary report still has reportable defects, complete the 21–24 month inspection. OC may then claim on the bond.",
    APT,
    false,
    ["Developer bond scheme — BPC"],
  ),
  item(
    "dlp-close",
    "defects-liability",
    "DLP close-out",
    "Confirm all listed defects are fixed or accepted. Extend DLP if the contract requires it when items remain open.",
  ),

  item(
    "fc-inspect",
    "final-certificate",
    "Final inspection after DLP",
    "Inspect remaining items. Do not issue a final certificate while contractual defects remain that the builder is obliged to fix.",
  ),
  item(
    "fc-issue",
    "final-certificate",
    "Final certificate",
    "Issue the final certificate. Domestic building warranty typically covers six years for structural defects and two years for non-structural defects.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995"],
  ),
  item(
    "fc-security",
    "final-certificate",
    "Release retention / security",
    "Release remaining security in accordance with the contract after final certificate.",
  ),
  item(
    "fc-archive",
    "final-certificate",
    "Archive project records",
    "Keep the agreement, permits, endorsed drawings, certificates, and this JSON package. Architects must document and maintain records.",
    ALL,
    true,
    ["ARBV Code — document and maintain records"],
  ),

  item(
    "poe-survey",
    "post-occupancy",
    "Occupant feedback",
    "Collect structured feedback after at least one winter and one summer where possible: comfort, storage, daylight, acoustics, operation of systems.",
  ),
  item(
    "poe-energy",
    "post-occupancy",
    "Energy and condensation check",
    "Compare bills or monitoring to the NatHERS intent. Look for condensation in bathrooms, robes and south-facing rooms.",
  ),
  item(
    "poe-landscape",
    "post-occupancy",
    "Landscape establishment",
    "Confirm canopy trees and deep-soil planting have established, irrigation works, and any planning landscape condition is still met.",
  ),
  item(
    "poe-lessons",
    "post-occupancy",
    "Lessons learned",
    "Note what to change on the next Victorian house, townhouse or apartment project. Store against this project, not only in someone’s inbox.",
    ALL,
    false,
  ),
];

function bot(
  stageId: string,
  name: string,
  title: string,
  description: string,
  firstTask: string,
): GrokBotBrief {
  return {
    id: `bot-${stageId}`,
    name,
    title,
    stageId,
    description,
    firstTask,
    plugins: ["web", "files"],
    approvalRules: [
      "Do not lodge permits, pay fees, or send emails to councils, surveyors or neighbours.",
      "Do not modify the project JSON except as a proposed patch presented for approval.",
      "Stop for approval before any external account sign-in, payment, or legal acceptance.",
    ],
  };
}

const GROKBOTS: GrokBotBrief[] = [
  bot(
    "pre-design",
    "Brief",
    "Pre-design researcher",
    "Turns a Victorian site into a briefing pack: title risks, zone/overlays, and which of Clauses 54, 55 or 58 will apply.",
    "Using only the attached project JSON and any title or planning-scheme files, produce a pre-design briefing note for this Victoria site. State typology (house, townhouse or apartment), likely planning permit trigger, applicable VPP clause, overlays, and missing surveys. Flag unknowns. Do not contact council. Stop after the note.",
  ),
  bot(
    "concept",
    "Sketch",
    "Concept tester",
    "Stress-tests a sketch against 7-star orientation, livable housing, parking and the relevant ResCode / BADS envelope.",
    "Read the project JSON and any concept PDFs. List envelope risks (height, setbacks, canopy, garden area, overlooking) and 7-star / livable-housing moves to make now. Return a punch-list mapped to checklist item ids. Do not redraw the scheme unless asked.",
  ),
  bot(
    "design-development",
    "Resolve",
    "Design-development coordinator",
    "Tracks consultants, NatHERS, stormwater and amenity diagrams before a planning freeze.",
    "From the project JSON, list which design-development checklist items still lack notes. Propose consultant RFPs and a lodging-readiness score. Do not email consultants.",
  ),
  bot(
    "town-planning",
    "Permit",
    "Planning permit packer",
    "Assembles a Clause 54 / 55 / 58 lodgement checklist and tracks RFI and permit conditions.",
    "Using the attached project JSON and template, draft a lodgement completeness list for this typology and storey count. Quote the relevant VPP clause. If a permit is already noted, extract condition types to watch (endorsed plans, landscape, ESD). Do not lodge.",
  ),
  bot(
    "documentation",
    "Working",
    "Documentation checker",
    "Diffs the building-permit set against endorsed planning drawings and NCC 2022 energy, livable housing and condensation.",
    "Compare notes in the project JSON against NCC 2022 items (7-star, livable housing, condensation, waterproofing). List gaps that would stall a Victorian building permit. Do not issue drawings.",
  ),
  bot(
    "tender",
    "Tender",
    "Tender comparitor",
    "Helps compare builder tenders on a like-for-like basis and checks registration and insurance.",
    "If tender notes or attachments exist, build a comparison table (price, program, exclusions, PC sums). Confirm the file notes whether the builder is registered and DBI is addressed. Do not appoint a builder.",
  ),
  bot(
    "contract-admin",
    "CA",
    "Contract administrator",
    "Tracks building permit, inspections, variations and occupancy. Remains impartial.",
    "Summarise open contract-administration items, including building permit, inspections and variations. For apartments, note whether the 2% developer bond scheme might apply given storeys and permit timing. Do not instruct the builder.",
  ),
  bot(
    "practical-completion",
    "PC",
    "Practical completion inspector",
    "Turns site notes and photos into a dated defects and incomplete-works list.",
    "From notes and any attached photos or PDFs, draft a practical completion defects list grouped by location. Mark items that should delay PC versus DLP. Do not certify PC.",
  ),
  bot(
    "defects-liability",
    "Defects",
    "Defects register",
    "Keeps the DLP register and, for captured apartment buildings, the bond inspection window.",
    "Rebuild the defects register from answers and notes. Diary DLP end. If typology is apartment and storeys > 3, outline the 15–18 and 21–24 month bond inspections as optional future items. Do not contact the builder.",
  ),
  bot(
    "final-certificate",
    "Final",
    "Final certificate clerk",
    "Checks DLP close-out, warranty start, and archive completeness.",
    "Confirm whether DLP close-out notes exist and list the archive (permits, certificates, this JSON package). Draft a final-certificate readiness paragraph. Do not issue the certificate.",
  ),
  bot(
    "post-occupancy",
    "POE",
    "Post-occupancy interviewer",
    "Structures seasonal POE questions and records lessons for the next Victorian residential project.",
    "Draft a short POE questionnaire tailored to this typology (house, townhouse or apartment) covering winter/summer comfort, energy, condensation, landscape and waste. Do not contact occupants.",
  ),
];

function withChecksum(
  template: Omit<TemplateDocument, "checksum">,
): TemplateDocument {
  const checksum = sha256Json(
    templateChecksumPayload(template as unknown as Record<string, unknown>),
  );
  return { ...template, checksum };
}

export const BUNDLED_TEMPLATE: TemplateDocument = withChecksum({
  format: TEMPLATE_FORMAT,
  formatVersion: FORMAT_VERSION,
  id: "vic-residential",
  version: "1.0.0",
  title: "Victoria residential — houses, townhouses and apartments",
  jurisdiction: "Victoria, Australia",
  description:
    "ARBV-aligned stages from pre-design through post-occupancy, with Clause 54 / 55 / 58, NCC 2022 (7-star and livable housing from 1 May 2024), and apartment developer-bond notes.",
  stages: STAGES,
  items: ITEMS,
  grokbots: GROKBOTS,
});

export function grokbotForStage(
  template: TemplateDocument,
  stageId: string,
): GrokBotBrief | undefined {
  return template.grokbots.find((entry) => entry.stageId === stageId);
}
