import type {
  ChecklistItem,
  GrokBotBrief,
  Stage,
  TemplateDocument,
  Typology,
} from "@/lib/types";
import { TEMPLATE_FORMAT, FORMAT_VERSION } from "@/lib/types";
import { resourcesForItem } from "@/lib/template/item-resources";
import { assessmentForItem } from "@/lib/template/item-assessments";
import {
  DELIVERABLE_CHECKS,
  STAGE_DELIVERABLES,
} from "@/lib/template/stage-deliverables";

const ALL: Typology[] = ["house", "townhouse", "apartment"];
const HOUSE: Typology[] = ["house"];
const TH: Typology[] = ["townhouse"];
const APT: Typology[] = ["apartment"];
const MULTI: Typology[] = ["townhouse", "apartment"];

const STAGES: Stage[] = [
  {
    id: "pre-design",
    number: 1,
    title: "Pre-design",
    summary:
      "Brief, title, planning context, budget and what is possible on the site before sketching.",
  },
  {
    id: "concept",
    number: 2,
    title: "Concept / sketch design",
    summary:
      "Options, massing and a preferred concept the client can sign, tested against Vic planning and 7-star orientation.",
  },
  {
    id: "design-development",
    number: 3,
    title: "Design development",
    summary:
      "Resolve the preferred scheme with consultants, materials, ESD and amenity so it is ready to lodge.",
  },
  {
    id: "town-planning",
    number: 4,
    title: "Town planning",
    summary:
      "Confirm whether a planning permit is required and run Clause 54, 55 or 58 through to endorsed plans.",
  },
  {
    id: "documentation",
    number: 5,
    title: "Construction documentation",
    summary:
      "Working drawings and specifications that match endorsed planning drawings and NCC 2025 for a building permit.",
  },
  {
    id: "tender",
    number: 6,
    title: "Tender and contractor selection",
    summary:
      "Issue the tender set, compare builders, and appoint under a written building contract.",
  },
  {
    id: "contract-admin",
    number: 7,
    title: "Building contract administration",
    summary:
      "Building permit, inspections, variations, progress certificates, and occupancy.",
  },
  {
    id: "practical-completion",
    number: 8,
    title: "Practical completion",
    summary:
      "Inspect, list defects, collect keys and manuals, and certify practical completion.",
  },
  {
    id: "defects-liability",
    number: 9,
    title: "Defects liability (post-occupancy)",
    summary:
      "Track and close defects during the contractual DLP and any apartment bond inspections.",
  },
  {
    id: "final-certificate",
    number: 10,
    title: "Final certificate",
    summary:
      "Issue the final certificate after DLP, start domestic building warranties, and archive the record.",
  },
  {
    id: "post-occupancy",
    number: 11,
    title: "Post-occupancy evaluation",
    summary:
      "Seasonal comfort, energy, landscape and lessons learned after people have lived in the building.",
  },
];

function item(
  id: string,
  stageId: string,
  title: string,
  detail: string,
  appliesTo: Typology[],
  required: boolean,
  references: string[],
  deliverableId?: string,
): ChecklistItem {
  if (references.length === 0 || references.some((value) => !value.trim())) {
    throw new Error(`Checklist item ${id} must cite at least one source`);
  }
  const resources = resourcesForItem(id);
  if (
    resources.length === 0 ||
    resources.some((entry) => !entry.label.trim() || !entry.url.startsWith("https://"))
  ) {
    throw new Error(`Checklist item ${id} must list at least one helper resource`);
  }
  const assessment = assessmentForItem(id);
  return {
    id,
    stageId,
    title,
    detail,
    appliesTo,
    required,
    references,
    resources,
    grokbotId: `bot-${stageId}`,
    ...(deliverableId ? { deliverableId } : {}),
    ...(assessment ? { assessment } : {}),
  };
}

const ITEMS: ChecklistItem[] = [
  item(
    "pd-arbv",
    "pre-design",
    "Confirm architect registration",
    "Check the architect (and any company) is registered with the Architects Registration Board of Victoria before engagement.",
    ALL,
    true,
    ["ARBV — Find an architect", "Victorian Architects Code of Professional Conduct"],
  ),
  item(
    "pd-agreement",
    "pre-design",
    "Written client–architect agreement",
    "Do not start work until a written agreement is signed. Record stages, fees, consultants, and whether planning and contract administration are included.",
    ALL,
    true,
    ["ARBV Guideline — Client-architect agreements"],
  ),
  item(
    "pd-brief",
    "pre-design",
    "Project brief",
    "Record household or dwelling mix, accessibility, working from home, storage, parking, landscape, budget range, and must-not-change constraints.",
    ALL,
    true,
    ["Architects Act 1991 (Vic)", "ARBV Guideline — Client–architect agreements"],
  ),
  item(
    "pd-title",
    "pre-design",
    "Title, easements, covenants and restrictions",
    "Obtain a current title, plan of subdivision, easements, covenants, S173 agreements, and any owners corporation rules that constrain siting or materials.",
    ALL,
    true,
    ["Land Use Victoria title search"],
  ),
  item(
    "pd-oc",
    "pre-design",
    "Owners corporation and common property",
    "Identify OC plan, common property, exclusive-use areas, and whether a special resolution is needed for works.",
    MULTI,
    true,
    ["Subdivision Act 1988", "Owners Corporations Act 2006"],
  ),
  item(
    "pd-planning-context",
    "pre-design",
    "Zone, overlays and planning scheme",
    "Record municipality, planning scheme, zone, overlays (heritage, flood, bushfire, special building, DDO, SLO, HO, BMO, LSIO, SBO) and whether a planning permit is likely.",
    ALL,
    true,
    ["Victoria Planning Provisions", "Planning scheme maps"],
  ),
  item(
    "pd-clauses",
    "pre-design",
    "Applicable residential clause",
    "House or small second dwelling: Clause 54 if a planning permit is required. Two or more dwellings / townhouses / low-rise apartments to three storeys: Clause 55 (Townhouse and Low-Rise Code). Apartments of five storeys or more: Clause 58. Confirm storeys and dwelling count.",
    ALL,
    true,
    ["VPP Clause 54", "VPP Clause 55", "VPP Clause 58"],
  ),
  item(
    "pd-bads",
    "pre-design",
    "BADS — which clause applies",
    "Better Apartments Design Standards (BADS) apply to apartment buildings. Use Clause 55.07 for apartments under five storeys (and Clause 55 / the Townhouse and Low-Rise Code if the building is three storeys or less). Use Clause 58 for five storeys or more, excluding a basement, and for apartments in commercial, activity-centre and similar zones. Record storeys excluding basement.",
    APT,
    true,
    ["Better Apartments Design Standards", "VPP Clause 55.07", "VPP Clause 58"],
  ),
  item(
    "pd-survey",
    "pre-design",
    "Feature and level survey",
    "Commission a site survey with levels, trees, crossovers, services, adjoining windows and secluded private open space relevant to ResCode.",
    ALL,
    true,
    ["VPP cl 54.01 / 55.01 neighbourhood and site description"],
  ),
  item(
    "pd-services",
    "pre-design",
    "Services and authority constraints",
    "Locate sewer, stormwater, water, power, gas, NBN, and any build-over or asset-protection requirements. Flag septic or unsewered lots.",
    ALL,
    true,
    ["Building Act 1993 (Vic)", "Water Act 1989 (Vic) — build-over assets"],
  ),
  item(
    "pd-hazards",
    "pre-design",
    "Bushfire, flood, contamination and heritage",
    "Record BAL if BMO or BAL construction may apply, flood levels, heritage citation, and potential contamination on infill lots.",
    ALL,
    true,
    ["AS 3959", "Building Regulations 2018", "Heritage Overlay"],
  ),
  item(
    "pd-budget",
    "pre-design",
    "Budget, program and GST",
    "Set a working construction budget, consultant budget, authority fees, and a program that includes planning time. Note GST treatment.",
    ALL,
    true,
    ["ARBV Guideline — Client–architect agreements", "A New Tax System (Goods and Services Tax) Act 1999 (Cth)"],
  ),
  item(
    "pd-neighbours",
    "pre-design",
    "Neighbourhood context photos",
    "Photograph streetscape, adjoining dwellings, existing trees, and likely overlooking/overshadowing interfaces.",
    ALL,
    false,
    ["VPP cl 54.01 / 55.01 neighbourhood and site description"],
  ),

  item(
    "cd-site-analysis",
    "concept",
    "Site analysis",
    "Sun path, prevailing wind, views, privacy, significant trees, slope, and street character. This feeds the design response.",
    ALL,
    true,
    ["Clause 54.01 / 55.01 neighbourhood and site description"],
  ),
  item(
    "cd-options",
    "concept",
    "Concept options",
    "Issue at least one preferred sketch scheme (and alternatives if the agreement requires). Record client comments against each.",
    ALL,
    true,
    ["ARBV Guideline — Client–architect agreements"],
  ),
  item(
    "cd-massing",
    "concept",
    "Height, setbacks and garden area",
    "Test building height, street setback, site coverage, permeability and garden-area requirements of the zone before locking a plan.",
    HOUSE,
    true,
    ["GRZ/NRZ garden area", "Clause 54 neighbourhood character standards"],
  ),
  item(
    "cd-cl55",
    "concept",
    "Clause 55 deemed-to-comply check",
    "Run an early check against street setback, height, side/rear setbacks, walls on boundaries, site coverage, access, tree canopy and front fence. Flag where the Townhouse and Low-Rise Code deemed-to-comply path is intended.",
    TH,
    true,
    ["Clause 55 Townhouse and Low-Rise Code (from 31 March 2025)"],
  ),
  item(
    "cd-canopy",
    "concept",
    "Tree canopy target",
    "Design for 10% canopy cover on sites up to 1,000 m² and 20% above 1,000 m², counting existing trees where they will be retained.",
    TH,
    true,
    ["Clause 55 tree canopy"],
  ),
  item(
    "cd-apartments",
    "concept",
    "BADS — dwelling mix and street interface",
    "Developments of ten or more dwellings should provide a range of dwelling sizes. Orient the building to the street; avoid blank walls, high front fences, and waste or carpark entries that dominate the street (Clause 58.02 / 55.07).",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 55.07", "Clause 58.02"],
  ),
  item(
    "cd-bads-communal",
    "concept",
    "BADS — communal open space",
    "Ten or more dwellings: at least 30 m² of communal outdoor open space. Thirteen or more: an extra 2.5 m² per dwelling or 220 m², whichever is less (indoor or outdoor). Locate communal outdoor space on the north side where practical, with winter solar access (Clause 58.03-2 / 58.03-3).",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.03-2", "Clause 55.07-2"],
  ),
  item(
    "cd-bads-pos",
    "concept",
    "BADS — private open space and balconies",
    "Give every dwelling secluded private open space to the BADS table (area and minimum dimension). Add 1.5 m² if a condenser sits on the balcony. South-facing living balconies may be 1.2 m deep; north-facing may be 1.7 m. Above about 40 m, extra living-room area can substitute for balcony area.",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.05-3", "Clause 55.07-9"],
  ),
  item(
    "cd-bads-layout",
    "concept",
    "BADS — functional layout",
    "Main bedroom at least 3 m × 3.4 m (10.2 m²). Other bedrooms at least 3 m × 3 m (9 m²). Living rooms: studio/one-bed 3.3 m wide and 10 m²; two or more bedrooms 3.6 m wide and 12 m² (Clause 58.07-1).",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.07-1"],
  ),
  item(
    "cd-bads-depth",
    "concept",
    "BADS — room depth and windows",
    "Single-aspect habitable rooms should not be deeper than 2.5 times the ceiling height. Open-plan single-aspect rooms may be up to 9 m where the ceiling is at least 2.7 m. Every habitable room needs a window in an external wall — not borrowed light from a corridor (Clause 58.07-2 / 58.07-3).",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.07-2", "Clause 58.07-3"],
  ),
  item(
    "cd-bads-setback",
    "concept",
    "BADS — setback, outlook and internal views",
    "Set the building back to the zone, overlay and BADS outlook standards. Limit views into existing and proposed private open space and habitable rooms (more than 50% of the space). Check building separation for daylight between wings.",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.04-1", "Clause 58.04-2"],
  ),
  item(
    "cd-bads-storage",
    "concept",
    "BADS — dwelling storage",
    "Each dwelling needs convenient, usable and secure storage to the BADS volume table (internal plus external or in a store). Do not count hanging-rail wardrobe space as the storage volume.",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.05-4"],
  ),
  item(
    "cd-energy",
    "concept",
    "Orientation for 7-star NatHERS",
    "Lock living-room solar access, glazing areas, shading and thermal mass so a 7-star NatHERS outcome is plausible. Victoria’s 7-star and whole-of-home requirements continue under NCC 2025, in force from 1 May 2026.",
    ALL,
    true,
    ["NCC 2025", "NatHERS 7-star (Vic)"],
  ),
  item(
    "cd-livable",
    "concept",
    "Livable housing path of travel",
    "Plan a step-free path, entrance width, and adaptable bathroom location. For Class 2, at least 50% of dwellings must meet the NCC livable housing provisions (or the higher VPP standard where it applies).",
    ALL,
    true,
    ["NCC 2025 Livable Housing Design", "ABCB Livable Housing Design Standard"],
  ),
  item(
    "cd-parking",
    "concept",
    "Parking, crossovers and waste",
    "Check Clause 52.06 parking, crossover locations, visitor parking, and whether waste collection is kerbside or on-site.",
    ALL,
    true,
    ["Clause 52.06"],
  ),
  item(
    "cd-signoff",
    "concept",
    "Client sign-off of preferred concept",
    "Written approval of the preferred concept, with a cost check against the brief, before design development.",
    ALL,
    true,
    ["ARBV Guideline — Client–architect agreements"],
  ),

  item(
    "dd-gas",
    "design-development",
    "Coordinated GA drawings",
    "Plans, sections and elevations at a scale suitable for planning, with levels, materials, and adjoining interfaces.",
    ALL,
    true,
    ["Planning and Environment Act 1987 (Vic)", "VPP cl 54 / 55 / 58 application requirements"],
  ),
  item(
    "dd-consultants",
    "design-development",
    "Consultant team engaged",
    "Appoint as needed: land surveyor, structural, civil/hydraulic, energy assessor, landscape, ESD, fire, acoustic, traffic, waste, geotech, quantity surveyor.",
    ALL,
    true,
    ["Architects Act 1991 (Vic)", "ARBV Code of Professional Conduct — competence and consultants"],
  ),
  item(
    "dd-nathers",
    "design-development",
    "Preliminary NatHERS and whole-of-home",
    "Run a preliminary 7-star rating and whole-of-home assessment. Adjust fabric before planning freeze.",
    ALL,
    true,
    ["NatHERS", "NCC 2025 energy"],
  ),
  item(
    "dd-storm",
    "design-development",
    "Stormwater and permeability",
    "STORM or MUSIC assessment, on-site detention if required, and permeability consistent with the planning standard.",
    ALL,
    true,
    ["Clause 53.18 / stormwater", "Melbourne Water", "local WSUD policy"],
  ),
  item(
    "dd-amenity",
    "design-development",
    "Overlooking, overshadowing and daylight",
    "Prepare diagrams for overlooking, overshadowing of secluded private open space, daylight to existing windows, and protection of existing rooftop solar.",
    ALL,
    true,
    ["Clause 54/55 amenity standards"],
  ),
  item(
    "dd-landscape",
    "design-development",
    "Landscape and deep soil",
    "Landscape concept with canopy trees, deep-soil volumes, and front-garden character. Apartments: deep-soil / canopy tables in 55.07 or 58.03.",
    ALL,
    true,
    ["Clause 55.07 / 58.03 landscaping"],
  ),
  item(
    "dd-bads-deep-soil",
    "design-development",
    "BADS — deep soil and canopy",
    "Provide canopy cover over deep-soil areas to the BADS landscaping table (Clause 58.03-5 / 55.07-4). Retain existing trees where possible; replace significant trees removed in the 12 months before lodgement. Show soil volume, depth and species, not only a planting image.",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.03-5", "Clause 55.07-4"],
  ),
  item(
    "dd-bess",
    "design-development",
    "ESD / BESS (apartments and larger townhouse sites)",
    "Where council policy requires it, prepare a BESS or equivalent ESD report covering energy, water, IEQ, stormwater and waste.",
    MULTI,
    false,
    ["local ESD policy", "BESS"],
  ),
  item(
    "dd-wind",
    "design-development",
    "BADS — wind impacts",
    "For five storeys or more (excluding a basement), demonstrate comfortable and safe wind conditions on public land, communal open space and private open space. Commission a qualified wind assessment where the standard requires it.",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.04-4"],
  ),
  item(
    "dd-acoustic",
    "design-development",
    "BADS — noise impacts",
    "Keep plant away from bedrooms. Address road and rail noise, apartment-to-apartment transfer, and specified internal noise levels on busy transport corridors (Clause 58.04-3).",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.04-3"],
  ),
  item(
    "dd-bads-entry",
    "design-development",
    "BADS — building entry and circulation",
    "Give the building a clear street identity. Entries, corridors, lifts and stairs should be visible, sheltered and sized for furniture and people with limited mobility (Clause 58.05-2).",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.05-2"],
  ),
  item(
    "dd-bads-vent",
    "design-development",
    "BADS — natural ventilation",
    "Maximise openable windows and doors. At least 40% of dwellings should have effective cross-ventilation with a complying breeze path (Clause 58.07-4).",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.07-4"],
  ),
  item(
    "dd-bads-materials",
    "design-development",
    "BADS — external walls and materials",
    "Specify durable external walls that weather well and suit the urban context. The design response must explain the finish selection (Clause 58.06-4 / 55.07-19).",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.06-4"],
  ),
  item(
    "dd-bads-access",
    "design-development",
    "BADS — accessible dwellings",
    "At least 50% of dwellings should meet BADS accessibility (850 mm entries, clear path to the main bedroom and bathroom, bathroom circulation). Align this set with the NCC livable-housing 50% for Class 2.",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58.05-1", "NCC 2025 Livable Housing Design"],
  ),
  item(
    "dd-waste",
    "design-development",
    "Waste management plan",
    "Apartment (and larger townhouse) waste rooms, collection vehicle path, and council waste policy.",
    MULTI,
    false,
    ["VPP cl 55.07 / 58 waste and recycling", "local waste management policy"],
  ),
  item(
    "dd-client-lodge",
    "design-development",
    "Client approval to lodge planning",
    "Confirm the scheme, cost update, and authority to lodge with council (or to proceed to building permit if no planning permit is required).",
    ALL,
    true,
    ["Planning and Environment Act 1987 (Vic)", "ARBV Guideline — Client–architect agreements"],
  ),

  item(
    "tp-need",
    "town-planning",
    "Confirm whether a planning permit is required",
    "Single dwellings on lots without overlays often proceed on a building permit only. Dual occupancy, townhouses, apartments, overlays and demolition commonly need a planning permit.",
    ALL,
    true,
    ["Planning and Environment Act 1987"],
  ),
  item(
    "tp-cl54",
    "town-planning",
    "Clause 54 assessment (house)",
    "If a permit is required for one dwelling or a small second dwelling, assess against Clause 54 including neighbourhood character, tree canopy and amenity (VC282 from 8 September 2025).",
    HOUSE,
    true,
    ["Clause 54", "Amendment VC282"],
  ),
  item(
    "tp-cl55",
    "town-planning",
    "Clause 55 assessment (townhouse / low-rise)",
    "Meet Clause 55 objectives. Where using deemed-to-comply standards, document each standard met. Otherwise provide an alternative design response against neighbourhood character policy.",
    TH,
    true,
    ["Clause 55", "Designing Better Medium Density Housing"],
  ),
  item(
    "tp-cl58",
    "town-planning",
    "BADS — Clause 58 assessment (5+ storeys)",
    "Lodge a Clause 58 assessment covering urban context, site layout, amenity impacts, on-site amenity, detailed design and internal amenity. Meet every objective; where a standard is varied, explain how the objective is still met.",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 58"],
  ),
  item(
    "tp-cl5507",
    "town-planning",
    "BADS — Clause 55.07 assessment (under 5 storeys)",
    "If the apartment building is under five storeys, assess against Clause 55.07 (and Clause 55 / the Townhouse and Low-Rise Code if three storeys or less). Mark N/A on a project if Clause 58 is the applicable path instead.",
    APT,
    true,
    ["Better Apartments Design Standards", "Clause 55.07"],
  ),
  item(
    "tp-nsd",
    "town-planning",
    "Neighbourhood and site description + design response",
    "Prepare the Clause 54.01 / 55.01 package: existing conditions, neighbourhood character and a design response that explains the scheme.",
    ALL,
    true,
    ["VPP cl 54.01 / 55.01"],
  ),
  item(
    "tp-set",
    "town-planning",
    "Planning drawing set",
    "Site plan, floor plans, elevations, sections, shadow diagrams, materials, landscape, and development summary (site coverage, permeability, garden area, canopy, parking).",
    ALL,
    true,
    ["Planning and Environment Act 1987 (Vic)", "VPP cl 54 / 55 / 58"],
  ),
  item(
    "tp-reports",
    "town-planning",
    "Supporting reports",
    "As required: traffic, waste, ESD/BESS, arborist, heritage, flood, bushfire, urban context, acoustic, wind, affordable housing.",
    ALL,
    false,
    ["Planning and Environment Act 1987 (Vic)", "VPP particular provisions"],
  ),
  item(
    "tp-lodge",
    "town-planning",
    "Lodge application and pay fees",
    "Lodge with the responsible authority, keep the application number, and diary statutory clocks.",
    ALL,
    true,
    ["Planning and Environment Act 1987 (Vic) s 47"],
  ),
  item(
    "tp-rfi",
    "town-planning",
    "Further information and advertising",
    "Respond to s54 further information. Track notice/advertising, objectors, and any consultation.",
    ALL,
    false,
    ["Planning and Environment Act ss 52, 54"],
  ),
  item(
    "tp-permit",
    "town-planning",
    "Planning permit and endorsed plans",
    "Receive the permit, read every condition, and obtain endorsed plans. Diary secondary consents, expiry, and plans-to-be-endorsed conditions.",
    ALL,
    true,
    ["Planning and Environment Act 1987 (Vic) ss 61, 68"],
  ),
  item(
    "tp-subdivision",
    "town-planning",
    "Subdivision and statement of compliance",
    "For townhouses (and apartment lots), run the plan of subdivision, OC schedule, and statement of compliance in parallel with construction as required.",
    MULTI,
    false,
    ["Subdivision Act 1988"],
  ),

  item(
    "doc-tp-match",
    "documentation",
    "Match endorsed town planning drawings",
    "Check every planning condition and endorsed dimension before issuing a building-permit set. Record any secondary consent needed.",
    ALL,
    true,
    ["Planning and Environment Act 1987 (Vic)", "Building Act 1993 (Vic) s 24"],
  ),
  item(
    "doc-working",
    "documentation",
    "Working drawings and specification",
    "Issue a coordinated architectural set and specification suitable for tender and for the building surveyor.",
    ALL,
    true,
    ["Building Act 1993 (Vic)", "NCC 2025"],
  ),
  item(
    "doc-ncc",
    "documentation",
    "NCC 2025 compliance notes",
    "Classify the building (Class 1a / 1b / 2 / 7a carpark etc.) and document performance solutions, fire, moisture, energy and accessibility against NCC 2025, in force in Victoria from 1 May 2026. Building work under a permit existing immediately before that date stays on the previous requirements unless the owner and relevant building surveyor agree to apply NCC 2025 (Building Act s 10). Plumbing: PCA 2025, including lead-free WaterMark products.",
    ALL,
    true,
    ["NCC 2025", "Building Act 1993 s 10"],
  ),
  item(
    "doc-energy",
    "documentation",
    "Final NatHERS 7-star and whole-of-home",
    "Final energy report for the building permit. New permits: NCC 2025 energy (7-star fabric plus whole-of-home). Permits existing before 1 May 2026 may remain on NCC 2022 under Building Act s 10.",
    ALL,
    true,
    ["NCC 2025", "NatHERS"],
  ),
  item(
    "doc-livable",
    "documentation",
    "Livable housing details",
    "Dimension step-free paths, 850 mm clear entries, sanitary facilities and adaptable bathrooms to the ABCB Livable Housing Design Standard (NCC 2025 Part H8). Apartments: identify the 50% of dwellings that meet Design A or B.",
    ALL,
    true,
    ["NCC 2025 Livable Housing Design"],
  ),
  item(
    "doc-condensation",
    "documentation",
    "Condensation management",
    "Detail climate-zone vapour permeance, wall membranes, and roof ventilation to NCC 2025. Most of Victoria is climate zone 6: a drained and ventilated wall cavity is required (also zones 7 and 8). Roof ventilation depends on whether insulation is parallel to the roof plane.",
    ALL,
    true,
    ["NCC 2025 condensation", "Housing Provisions Part 10.8"],
  ),
  item(
    "doc-structure",
    "documentation",
    "Structural, civil and services drawings",
    "Coordinated structure, stormwater, sewer, electrical, mechanical and fire drawings issued as part of the permit set.",
    ALL,
    true,
    ["Building Act 1993 (Vic)", "NCC 2025"],
  ),
  item(
    "doc-waterproofing",
    "documentation",
    "Waterproofing and wet areas",
    "Specify AS 3740 wet-area systems, inspection hold points, and AS 4654 external waterproofing for roofs, balconies and terraces over habitable rooms (NCC 2025 Part H2).",
    ALL,
    true,
    ["AS 3740", "AS 4654", "NCC 2025 Part H2"],
  ),
  item(
    "doc-part5",
    "documentation",
    "Part 5 siting vs planning permit",
    "Where no planning permit exists, check Part 5 of the Building Regulations (siting). Where a planning permit exists, apply regulation 68 so the building permit is not inconsistent with the planning permit.",
    HOUSE,
    true,
    ["Building Regulations 2018 Part 5", "reg 68"],
  ),
  item(
    "doc-manual",
    "documentation",
    "Building manual inputs",
    "Collect information needed for the building manual / operations information that the 2025 inspection and manual reforms expect at occupancy.",
    ALL,
    false,
    ["Building Amendment (Building Manuals and Mandatory Inspections) Regulations 2025"],
  ),

  item(
    "tn-set",
    "tender",
    "Tender set issued",
    "Issue drawings, specification, planning permit, and known site constraints. Record tender closing date.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic)", "ARBV Guideline — Client–architect agreements"],
  ),
  item(
    "tn-rfi",
    "tender",
    "Tender RFIs",
    "Answer builder queries in writing and issue addenda to all tenderers.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic)", "ARBV Code of Professional Conduct"],
  ),
  item(
    "tn-compare",
    "tender",
    "Tender comparison",
    "Compare price, program, qualifications, PC sums, and exclusions on the same basis.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic)", "ARBV Code of Professional Conduct"],
  ),
  item(
    "tn-builder",
    "tender",
    "Builder registration and insurance",
    "Confirm VBA/BPC registration, domestic building insurance where required, and public liability.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995", "Building and Plumbing Commission"],
  ),
  item(
    "tn-contract",
    "tender",
    "Building contract executed",
    "Execute a written contract (ABIC, HIA or other) with the drawings and spec listed. Architect as contract administrator if engaged for that stage.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic) s 31"],
  ),
  item(
    "tn-rbs",
    "tender",
    "Appoint relevant building surveyor",
    "Client appoints a registered building surveyor. Do not let the builder appoint the RBS for the client.",
    ALL,
    true,
    ["Building Act 1993"],
  ),

  item(
    "ca-permit",
    "contract-admin",
    "Building permit issued",
    "Building permit received before work starts. Check it lists the correct drawings, stages, and mandatory notification stages.",
    ALL,
    true,
    ["Building Act 1993"],
  ),
  item(
    "ca-inspections",
    "contract-admin",
    "Mandatory inspections program",
    "Diary foundation, framing, waterproofing, occupancy and any additional 2025 notification stages. Builders must notify the RBS before covering work.",
    ALL,
    true,
    ["Building Regulations 2018 mandatory notifications"],
  ),
  item(
    "ca-meetings",
    "contract-admin",
    "Site meetings and minutes",
    "Minute directions, RFIs, and quality issues. Architect remains impartial if administering the contract.",
    ALL,
    true,
    ["ARBV Code — administer building contracts impartially"],
  ),
  item(
    "ca-variations",
    "contract-admin",
    "Variations",
    "Price and approve variations in writing before the work proceeds. Keep a running cost report.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic)", "Building and Construction Industry Security of Payment Act 2002 (Vic)"],
  ),
  item(
    "ca-claims",
    "contract-admin",
    "Progress claims and certificates",
    "Assess claims, issue certificates, and track retention or security under the contract.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic)", "Building and Construction Industry Security of Payment Act 2002 (Vic)"],
  ),
  item(
    "ca-oc",
    "contract-admin",
    "Occupancy permit or final inspection",
    "RBS issues an occupancy permit (or certificate of final inspection). Apartments: occupancy before residents move in, typically for the building / each part as applicable.",
    ALL,
    true,
    ["Building Act 1993 occupancy permit"],
  ),
  item(
    "ca-bond",
    "contract-admin",
    "Apartment developer bond (if captured)",
    "For residential apartment buildings over three storeys with a building permit issued from 1 July 2027, lodge a 2% bond with the BPC before applying for occupancy. Notice to BPC as required. Transitional: regulations from 1 July 2026.",
    APT,
    false,
    ["Building Legislation Amendment (Buyer Protections) Act 2025"],
  ),
  item(
    "ca-oc-setup",
    "contract-admin",
    "Owners corporation set-up",
    "OC registered, insurance, first meeting, common property schedule, and building manual handed over.",
    MULTI,
    false,
    ["Owners Corporations Act 2006 (Vic)", "Subdivision Act 1988 (Vic)"],
  ),

  item(
    "pc-inspect",
    "practical-completion",
    "Practical completion inspection",
    "Architect inspects against the contract documents. Major defects delay PC; minor defects go on the list.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic)", "ARBV Code of Professional Conduct — contract administration"],
  ),
  item(
    "pc-list",
    "practical-completion",
    "Defects and incomplete works list",
    "Issue a dated list. Builder must close items. Occupancy permit does not waive contractual defects.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic)", "Building Act 1993 (Vic) occupancy permit"],
  ),
  item(
    "pc-handover",
    "practical-completion",
    "Keys, warranties, as-builts and manuals",
    "Collect keys, appliance warranties, cleaning, as-built services drawings, operation manuals, and the building manual.",
    ALL,
    true,
    ["Building Act 1993 (Vic)", "Building Amendment (Building Manuals and Mandatory Inspections) Regulations 2025 (Vic)"],
  ),
  item(
    "pc-certificate",
    "practical-completion",
    "Certificate of practical completion",
    "Issue PC. This starts the defects liability period. Record the date in the project JSON.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),

  item(
    "dlp-period",
    "defects-liability",
    "Defects liability period diary",
    "Record DLP start (PC date) and end. Typical residential contracts use 12 months; check the executed contract.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),
  item(
    "dlp-track",
    "defects-liability",
    "Defects register",
    "Log each defect with date, location, photo, item id, and close-out date. Empty notes are allowed; do not delete closed items.",
    ALL,
    true,
    ["ARBV Code of Professional Conduct — document and maintain records"],
  ),
  item(
    "dlp-bond-prelim",
    "defects-liability",
    "Apartment bond preliminary inspection (15–18 months)",
    "If the developer bond scheme applies, arrange the qualified building assessor inspection 15–18 months after occupancy and give the developer an opportunity to rectify.",
    APT,
    false,
    ["Developer bond scheme — BPC"],
  ),
  item(
    "dlp-bond-final",
    "defects-liability",
    "Apartment bond final inspection (21–24 months)",
    "If the preliminary report still has reportable defects, complete the 21–24 month inspection. OC may then claim on the bond.",
    APT,
    false,
    ["Developer bond scheme — BPC"],
  ),
  item(
    "dlp-close",
    "defects-liability",
    "DLP close-out",
    "Confirm all listed defects are fixed or accepted. Extend DLP if the contract requires it when items remain open.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic)"],
  ),

  item(
    "fc-inspect",
    "final-certificate",
    "Final inspection after DLP",
    "Inspect remaining items. Do not issue a final certificate while contractual defects remain that the builder is obliged to fix.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic)", "ARBV Code of Professional Conduct"],
  ),
  item(
    "fc-issue",
    "final-certificate",
    "Final certificate",
    "Issue the final certificate. Domestic building warranty typically covers six years for structural defects and two years for non-structural defects.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995"],
  ),
  item(
    "fc-security",
    "final-certificate",
    "Release retention / security",
    "Release remaining security in accordance with the contract after final certificate.",
    ALL,
    true,
    ["Domestic Building Contracts Act 1995 (Vic)", "Building and Construction Industry Security of Payment Act 2002 (Vic)"],
  ),
  item(
    "fc-archive",
    "final-certificate",
    "Archive project records",
    "Keep the agreement, permits, endorsed drawings, certificates, and this JSON package. Architects must document and maintain records.",
    ALL,
    true,
    ["ARBV Code — document and maintain records"],
  ),

  item(
    "poe-survey",
    "post-occupancy",
    "Occupant feedback",
    "Collect structured feedback after at least one winter and one summer where possible: comfort, storage, daylight, acoustics, operation of systems.",
    ALL,
    true,
    ["ARBV Code of Professional Conduct", "NCC 2025 energy and condensation intent"],
  ),
  item(
    "poe-energy",
    "post-occupancy",
    "Energy and condensation check",
    "Compare bills or monitoring to the NatHERS intent. Look for condensation in bathrooms, robes and south-facing rooms.",
    ALL,
    true,
    ["NCC 2025", "NatHERS 7-star (Vic)"],
  ),
  item(
    "poe-landscape",
    "post-occupancy",
    "Landscape establishment",
    "Confirm canopy trees and deep-soil planting have established, irrigation works, and any planning landscape condition is still met.",
    ALL,
    true,
    ["VPP cl 55.07 / 58.03 landscaping", "Planning and Environment Act 1987 (Vic) permit conditions"],
  ),
  item(
    "poe-lessons",
    "post-occupancy",
    "Lessons learned",
    "Note what to change on the next Victorian house, townhouse or apartment project. Store against this project, not only in someone’s inbox.",
    ALL,
    false,
    ["ARBV Code of Professional Conduct — document and maintain records"],
  ),
  ...DELIVERABLE_CHECKS.map((entry) =>
    item(
      entry.id,
      entry.stageId,
      entry.title,
      entry.detail,
      entry.appliesTo,
      entry.required,
      entry.references,
      entry.deliverableId,
    ),
  ),
];

function bot(
  stageId: string,
  name: string,
  title: string,
  description: string,
  firstTask: string,
): GrokBotBrief {
  return {
    id: `bot-${stageId}`,
    name,
    title,
    stageId,
    description,
    firstTask,
    plugins: ["web", "files"],
    approvalRules: [
      "Do not lodge permits, pay fees, or send emails to councils, surveyors or neighbours.",
      "Do not modify the project JSON except as a proposed patch presented for approval.",
      "Stop for approval before any external account sign-in, payment, or legal acceptance.",
    ],
  };
}

const GROKBOTS: GrokBotBrief[] = [
  bot(
    "pre-design",
    "Brief",
    "Pre-design researcher",
    "Turns a Victorian site into a briefing pack: title risks, zone/overlays, Clauses 54 / 55 / 58, and BADS for apartments.",
    "Using only the attached project JSON and any title or planning-scheme files, produce a pre-design briefing note for this Victoria site. State typology (house, townhouse or apartment), likely planning permit trigger, applicable VPP clause, overlays, and missing surveys. Flag unknowns. Do not contact council. Stop after the note.",
  ),
  bot(
    "concept",
    "Sketch",
    "Concept tester",
    "Stress-tests a sketch against 7-star orientation, livable housing, parking and the relevant ResCode / BADS envelope.",
    "Read the project JSON and any concept PDFs. List envelope risks (height, setbacks, canopy, garden area, overlooking) and, for apartments, BADS communal open space, balcony sizes, room depth and functional layout. Return a punch-list mapped to checklist item ids. Do not redraw the scheme unless asked.",
  ),
  bot(
    "design-development",
    "Resolve",
    "Design-development coordinator",
    "Tracks consultants, NatHERS, stormwater and amenity diagrams before a planning freeze.",
    "From the project JSON, list which design-development checklist items still lack notes. Propose consultant RFPs and a lodging-readiness score. Do not email consultants.",
  ),
  bot(
    "town-planning",
    "Permit",
    "Planning permit packer",
    "Assembles a Clause 54 / 55 / 58 lodgement checklist and tracks RFI and permit conditions.",
    "Using the attached project JSON and template, draft a lodgement completeness list for this typology and storey count. Quote the relevant VPP clause. If a permit is already noted, extract condition types to watch (endorsed plans, landscape, ESD). Do not lodge.",
  ),
  bot(
    "documentation",
    "Working",
    "Documentation checker",
    "Diffs the building-permit set against endorsed planning drawings and NCC 2025 energy, livable housing and condensation.",
    "Compare notes in the project JSON against NCC 2025 items (7-star, livable housing, condensation, waterproofing). List gaps that would stall a Victorian building permit. Note Building Act s 10 if a pre-1 May 2026 permit still sits on NCC 2022. Do not issue drawings.",
  ),
  bot(
    "tender",
    "Tender",
    "Tender comparitor",
    "Helps compare builder tenders on a like-for-like basis and checks registration and insurance.",
    "If tender notes or attachments exist, build a comparison table (price, program, exclusions, PC sums). Confirm the file notes whether the builder is registered and DBI is addressed. Do not appoint a builder.",
  ),
  bot(
    "contract-admin",
    "CA",
    "Contract administrator",
    "Tracks building permit, inspections, variations and occupancy. Remains impartial.",
    "Summarise open contract-administration items, including building permit, inspections and variations. For apartments, note whether the 2% developer bond scheme might apply given storeys and permit timing. Do not instruct the builder.",
  ),
  bot(
    "practical-completion",
    "PC",
    "Practical completion inspector",
    "Turns site notes and photos into a dated defects and incomplete-works list.",
    "From notes and any attached photos or PDFs, draft a practical completion defects list grouped by location. Mark items that should delay PC versus DLP. Do not certify PC.",
  ),
  bot(
    "defects-liability",
    "Defects",
    "Defects register",
    "Keeps the DLP register and, for captured apartment buildings, the bond inspection window.",
    "Rebuild the defects register from answers and notes. Diary DLP end. If typology is apartment and storeys > 3, outline the 15–18 and 21–24 month bond inspections as optional future items. Do not contact the builder.",
  ),
  bot(
    "final-certificate",
    "Final",
    "Final certificate clerk",
    "Checks DLP close-out, warranty start, and archive completeness.",
    "Confirm whether DLP close-out notes exist and list the archive (permits, certificates, this JSON package). Draft a final-certificate readiness paragraph. Do not issue the certificate.",
  ),
  bot(
    "post-occupancy",
    "POE",
    "Post-occupancy interviewer",
    "Structures seasonal POE questions and records lessons for the next Victorian residential project.",
    "Draft a short POE questionnaire tailored to this typology (house, townhouse or apartment) covering winter/summer comfort, energy, condensation, landscape and waste. Do not contact occupants.",
  ),
];

function withChecksum(
  template: Omit<TemplateDocument, "checksum">,
): TemplateDocument {
  return {
    ...template,
    checksum:
      "98d45ded619d7b2fb71c9bd9e7e9fdf66fb66e0440137da96662e25d1c407a31",
  };
}

export const BUNDLED_TEMPLATE: TemplateDocument = withChecksum({
  format: TEMPLATE_FORMAT,
  formatVersion: FORMAT_VERSION,
  id: "vic-residential",
  version: "1.0.7",
  title: "Victoria residential — houses, townhouses and apartments",
  jurisdiction: "Victoria, Australia",
  description:
    "ARBV-aligned stages from pre-design through post-occupancy, with a drawing or document and associated checklist on each stage, Clause 54 / 55 / 58, Better Apartments Design Standards (BADS) on apartment items, NCC 2025 (in force in Victoria from 1 May 2026), and apartment developer-bond notes.",
  stages: STAGES,
  items: ITEMS,
  grokbots: GROKBOTS,
  deliverables: STAGE_DELIVERABLES,
});

export function grokbotForStage(
  template: TemplateDocument,
  stageId: string,
): GrokBotBrief | undefined {
  return template.grokbots.find((entry) => entry.stageId === stageId);
}
